import {test,expect} from '@playwright/test'
test('reviewed opaque surfaces receive exact policies and retain independent realms',async({page,context})=>{
 const documents=new Map<string,{html:string;csp:string;permissionsPolicy:string}>();page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/frame-documents/')){const value=request.postDataJSON();documents.set(value.frameId,value)}})
 await context.addCookies([{name:'secret',value:'parent',url:'http://127.0.0.1:18543'}])
 await page.goto('/?frames=1')
 await expect(page.getByText('Frame registry: ready')).toBeVisible({timeout:15000})
 const first=page.getByRole('region',{name:'Surface first'}).locator('iframe'),second=page.getByRole('region',{name:'Surface second'}).locator('iframe')
 await expect(first).toHaveCount(1);await expect(second).toHaveCount(1)
 const a=first.contentFrame(),b=second.contentFrame();await expect(a.getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});await expect(b.getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000})
 await a.getByRole('button',{name:'Frame count 0'}).click();await expect(a.getByRole('button',{name:'Frame count 1'})).toBeVisible();await expect(b.getByRole('button',{name:'Frame count 0'})).toBeVisible()
 const src=await first.getAttribute('src');const frame=page.frames().find(frame=>frame.url()===src)!;const proof=await frame.evaluate(()=> (globalThis as any).frameProof)
 expect(proof).toMatchObject({parent:false,storage:false,cookie:false,exact:'reviewed-frame-bytes'})
 const response=await page.request.get(src!);const headers=response.headers();const html=await response.text();const delivered=documents.get(src!.split('/').at(-1)!);expect(delivered).toBeDefined();expect(html).toBe(delivered!.html);expect(headers['content-security-policy']).toBe(delivered!.csp);expect(headers['permissions-policy']).toBe(delivered!.permissionsPolicy);expect(headers['content-security-policy']).toContain("connect-src 'none'");expect(headers['content-security-policy']).toContain("'sha256-");expect(headers['permissions-policy']).toContain('camera=()');expect(html).toContain(headers['content-security-policy'].replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;'));expect(headers['referrer-policy']).toBe('no-referrer');await page.screenshot({path:'../.scratch/opaque-frame-consumer.png',fullPage:true});expect((await page.request.delete(src!)).status()).toBe(403);expect((await page.request.post('/api/frame-documents/',{data:delivered})).status()).toBe(403);expect((await page.request.post('/api/frame-documents/',{headers:{Origin:'http://127.0.0.1:18543'},data:{...delivered,csp:"default-src *"}})).status()).toBe(403);expect((await page.request.get(src!)).status()).toBe(200);expect(await first.getAttribute('sandbox')).toBe('allow-scripts')
 await page.getByRole('button',{name:'Dispose first surface'}).click();await expect(first).toHaveCount(0);await expect(b.getByRole('button',{name:'Frame count 0'})).toBeVisible()
 await page.getByRole('button',{name:'Unload frame owner'}).click();await expect(second).toHaveCount(0);await expect(page.getByRole('region',{name:'Surface stable'}).locator('iframe').contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible();await expect(page.getByText('Embedded host view remains available')).toBeVisible()
 await expect.poll(async()=> (await page.request.get(src!)).status()).toBe(404)
})

test('frame typed navigation/modal/action denial and late producer cancellation use the shared gateway',async({page})=>{
 await page.goto('/?frames=1');await expect(page.getByText('Frame registry: ready')).toBeVisible({timeout:15000})
 const surface=page.getByRole('region',{name:'Surface first'}).locator('iframe').contentFrame();await expect(surface.getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000})
 await surface.getByRole('button',{name:'Frame navigate'}).click();await expect(page.getByText('Host route: detail')).toBeVisible()
 await surface.getByRole('button',{name:'Frame simulate'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('simulated success')
 await surface.getByRole('button',{name:'Frame modal'}).click();await expect(page.getByRole('dialog',{name:'Frame fixture modal'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByRole('button',{name:'Hold fixture producer'}).click();await surface.getByRole('button',{name:'Frame simulate'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('pending')
 await page.getByRole('button',{name:'Change frame invocation'}).click();await expect(surface.getByText('Frame outcome: unknown-outcome')).toBeVisible();await expect(page.getByRole('region',{name:'Frame receipts'})).toBeEmpty()
 await page.getByRole('button',{name:'Complete frame producer'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).toBeEmpty();await expect(surface.getByText('Frame outcome: unknown-outcome')).toBeVisible()
 await page.getByRole('button',{name:'Deny fixture actions'}).click();await surface.getByRole('button',{name:'Frame simulate'}).click();await expect(surface.getByText('Frame outcome: refused')).toBeVisible();await expect(page.getByRole('region',{name:'Frame receipts'})).toBeEmpty()
 const url=await page.getByRole('region',{name:'Surface first'}).locator('iframe').getAttribute('src');const frame=page.frames().find(frame=>frame.url()===url)!;expect(await frame.evaluate(()=> (globalThis as any).pluginFrame.invoke('undeclared',{type:'command',command:'frame-tools/run',arguments:{}}))).toMatchObject({status:'refused'})
})
test('generation replacement releases old documents and resets frame state',async({page})=>{
 await page.goto('/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe');const surface=first.contentFrame();await expect(surface.getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});await surface.getByRole('button',{name:'Frame count 0'}).click();const old=await first.getAttribute('src');await page.getByRole('button',{name:'Hold fixture producer'}).click();await surface.getByRole('button',{name:'Frame simulate'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('pending')
 await page.getByRole('button',{name:'Replace generation'}).click();await expect.poll(()=>first.getAttribute('src')).not.toBe(old);await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});await expect.poll(async()=> (await page.request.get(old!)).status()).toBe(404);await expect(page.getByText('Embedded host view remains available')).toBeVisible();await page.getByRole('button',{name:'Complete frame producer'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).not.toContainText('simulated')
})
test('failed document policy never executes a main-origin fallback',async({page})=>{
 await page.route('**/api/frame-documents/',route=>route.fulfill({status:403,body:'policy unavailable'}))
 await page.goto('/?frames=1');await expect(page.getByText('Frame registry: frame load refused')).toBeVisible({timeout:15000});await expect(page.locator('iframe')).toHaveCount(0);await expect(page.getByRole('button',{name:'Frame count 0'})).toHaveCount(0);await expect(page.getByRole('region',{name:'Frame diagnostics'})).toContainText('policy-unavailable');await expect(page.getByText('Embedded host view remains available')).toBeVisible()
})
test('main-origin remains refused until explicitly authorized after old frames retire',async({page})=>{
 await page.goto('/?frames=1');await expect(page.getByRole('region',{name:'Surface first'}).locator('iframe').contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000})
 await page.getByRole('button',{name:'Request unauthorized main-origin'}).click();await expect(page.getByText('Frame registry: frame load refused')).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0);await expect(page.getByRole('button',{name:'Frame count 0'})).toHaveCount(0);expect(await page.evaluate(()=>typeof(globalThis as any).frameProof)).toBe('undefined')
 await page.getByRole('button',{name:'Authorize reviewed main-origin'}).click();await expect(page.getByText('Frame registry: ready')).toBeVisible();await expect(page.getByRole('region',{name:'Surface first'}).getByRole('button',{name:'Frame count 0'})).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0);await expect(page.getByRole('region',{name:'Frame diagnostics'})).toContainText('main-origin-ambient-authority');expect(await page.evaluate(()=> (globalThis as any).frameProof.parent)).toBe(true)
})
test('frame context updates cancel pending producer callbacks and keep sibling realms alive',async({page})=>{
 await page.goto('/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe').contentFrame();const second=page.getByRole('region',{name:'Surface second'}).locator('iframe').contentFrame();await expect(first.getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});await second.getByRole('button',{name:'Frame count 0'}).click()
 await page.getByRole('button',{name:'Hold fixture producer'}).click();await first.getByRole('button',{name:'Frame simulate'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('pending');await page.getByRole('button',{name:'Change frame context'}).click();await expect(first.getByText('Frame context: first: frame-context-b')).toBeVisible();await expect(first.getByText('Frame outcome: unknown-outcome')).toBeVisible();await expect(second.getByRole('button',{name:'Frame count 1'})).toBeVisible();await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('cancelled');await page.getByRole('button',{name:'Complete frame producer'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).not.toContainText('simulated')
})

test('actual frame document denies fetch/subresources/forms/popups/top navigation',async({page})=>{
 let popups=0;page.on('popup',()=>popups++)
 await page.goto('/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe');await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});const url=await first.getAttribute('src');const frame=page.frames().find(frame=>frame.url()===url)!
 const results=await frame.evaluate(async origin=>{const outcomes:string[]=[];try{await fetch(origin+'/api/blocked-frame/fetch');outcomes.push('fetch-allowed')}catch{outcomes.push('fetch-denied')};const image=new Image();image.src=origin+'/api/blocked-frame/image';document.body.append(image);const form=document.createElement('form');form.action=origin+'/api/blocked-frame/form';document.body.append(form);form.submit();outcomes.push(window.open(origin+'/api/blocked-frame/popup')===null?'popup-denied':'popup-opened');try{top!.location.href=origin+'/api/blocked-frame/top';outcomes.push('top-allowed')}catch{outcomes.push('top-denied')};return outcomes},'http://127.0.0.1:18543')
 expect(results).toEqual(['fetch-denied','popup-denied','top-denied']);expect(await (await page.request.get('/api/frame-egress')).json()).toEqual({received:0});expect(popups).toBe(0);await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible();await expect(page).toHaveURL('http://127.0.0.1:18543/?frames=1')
})

for(const cancellation of ['scope','target','caller'])test(`frame ${cancellation} cancellation prevents a delayed producer outcome`,async({page})=>{
 await page.goto('/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe');await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});const url=await first.getAttribute('src');const frame=page.frames().find(frame=>frame.url()===url)!
 await page.getByRole('button',{name:'Hold fixture producer'}).click();await frame.evaluate(()=>{(globalThis as any).pendingFixture=(globalThis as any).pluginFrame.invoke('run',{type:'command',command:'frame-tools/run',arguments:{}})})
 await expect(page.getByRole('region',{name:'Frame receipts'})).toContainText('pending')
 if(cancellation==='scope')await page.getByRole('button',{name:'Change frame scope'}).click();else if(cancellation==='target')await page.getByRole('button',{name:'Unload frame target'}).click();else await frame.evaluate(()=> (globalThis as any).pluginFrame.cancel('1'))
 expect(await frame.evaluate(()=> (globalThis as any).pendingFixture)).toMatchObject({status:'unknown-outcome'})
 await page.getByRole('button',{name:'Complete frame producer'}).click();await expect(page.getByRole('region',{name:'Frame receipts'})).not.toContainText('simulated');await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible();await expect(page.getByText('Embedded host view remains available')).toBeVisible()
})
test('self-navigation egress is observed before the frame session is revoked',async({page})=>{
 const observed:string[]=[];page.on('request',request=>{if(request.url().includes('frame-self-navigation'))observed.push(request.url())})
 await page.goto('/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe'),second=page.getByRole('region',{name:'Surface second'}).locator('iframe');await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});const url=await first.getAttribute('src');const frame=page.frames().find(frame=>frame.url()===url)!
 await frame.evaluate(()=>{location.href='http://127.0.0.1:18543/healthz?frame-self-navigation'}).catch(()=>{})
 await expect(first).toHaveCount(0);await expect(page.getByRole('region',{name:'Surface first'}).getByText('Plugin view failed.')).toBeVisible();expect(observed).toHaveLength(1);await expect(second.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible()
})

test('development subpath uses the same opaque controller and explicit parent-origin policy',async({page})=>{
 await page.goto('http://127.0.0.1:18544/proof/?frames=1');const first=page.getByRole('region',{name:'Surface first'}).locator('iframe');await expect(first.contentFrame().getByRole('button',{name:'Frame count 0'})).toBeVisible({timeout:15000});await first.contentFrame().getByRole('button',{name:'Frame count 0'}).click();await expect(first.contentFrame().getByRole('button',{name:'Frame count 1'})).toBeVisible();const src=await first.getAttribute('src');expect(src).toMatch(/^http:\/\/127\.0\.0\.1:18544\/api\/frame-documents\//);const response=await page.request.get(src!);expect(response.headers()['content-security-policy']).toContain("connect-src 'none'");await expect(page.getByText('Embedded host view remains available')).toBeVisible()
})
