import { test, expect, type Page } from '@playwright/test';
async function seek(page: Page, index: number) { const s = page.getByRole('slider', { name: 'Playback boundary' }); await s.focus(); await page.keyboard.press('Home'); for (let i = 0; i < index; i++)
    await page.keyboard.press('ArrowRight'); await expect(page.getByRole('status', { name: 'Playback clock' })).toContainText(`Frame ${index}/3`); }
test.beforeEach(async ({ page }) => { await page.goto('/?widgets=1'); await expect(page.getByRole('heading', { name: 'Controlled visual widgets proof' })).toBeVisible(); await expect(page.getByRole('button', { name: 'Stable local count 0' })).toBeVisible(); });
test('real six exports show prefix values, zero scale distinction, null and record proportions', async ({ page }) => { const proof = page.getByRole('region', { name: 'Controlled visual widgets' }); await expect(proof).toContainText('Actual observed peak 0'); await expect(proof).toContainText('peak 1'); await expect(proof).toContainText('Uncollected'); await expect(proof.locator('tbody tr')).toHaveCount(1); await expect(proof).not.toContainText('final fixture outcome'); await seek(page, 3); await expect(proof.locator('tbody tr')).toHaveCount(4); await expect(proof).toContainText('Actual observed peak 5'); const donut = proof.locator('[aria-label="Known record classes"]'); await expect(donut).toContainText('4 recorded rows'); await expect(donut.locator('svg circle')).toHaveCount(3); const lengths = await donut.locator('svg circle[stroke-dasharray]').evaluateAll(nodes => nodes.map(node => Number(node.getAttribute('stroke-dasharray')!.split(' ')[0]))); expect(lengths[0] / lengths[1]).toBeCloseTo(3, 6); await expect(donut).toContainText('3 · 75%'); await expect(donut).toContainText('1 · 25%'); await expect(proof.locator('[aria-label="Newest recorded first"] li').first()).toContainText('final fixture outcome'); await page.getByRole('button', { name: /source-a: final fixture outcome/ }).click(); await expect(page.getByRole('status', { name: 'Widget selection' })).toContainText('final fixture outcome'); await page.getByRole('button', { name: 'Toggle secondary signal' }).click(); await expect(proof.locator('thead')).not.toContainText('Secondary'); await page.getByRole('button', { name: 'Toggle compact widgets' }).click(); await expect(proof.locator('.widgets-grid')).toHaveClass(/widgets-compact/); await expect(page.getByRole('status', { name: 'Widget selection' })).toContainText('final fixture outcome'); await page.getByRole('button', { name: 'Toggle compact widgets' }).click(); await page.screenshot({ path: '../.scratch/controlled-widgets-desktop.png', fullPage: true }); await page.locator('.widgets-grid').evaluate(el => el.scrollIntoView({ block: 'start' })); await page.screenshot({ path: '../.scratch/controlled-widgets-desktop-viewport.png', fullPage: false }); });
for (const change of ['generation', 'owner', 'source', 'context'])
    test(`actual ${change} retires local widget selection and settings with stable lease policy`, async ({ page }) => { await seek(page, 2); await page.getByRole('button', { name: 'Stable local count 0' }).click(); await page.getByRole('button', { name: /source-a: review ready/ }).click(); await page.getByRole('button', { name: 'Toggle secondary signal' }).click(); await page.getByRole('button', { name: 'Toggle compact widgets' }).click(); const old = await page.getByText(/Widgets lease:/).textContent(); await page.locator('link[href*="fake-ops/g1/style.css"]').evaluate(el => (window as any).oldWidgetStyle = el); await page.getByRole('button', { name: change === 'generation' ? 'Replace widgets generation' : change === 'owner' ? 'Unload playback plugin owner' : change === 'source' ? 'Retire playback source' : 'Switch playback context' }).click(); if (change === 'owner') {
        await expect(page.getByRole('region', { name: 'Controlled visual widgets' })).toContainText('No current widget contribution');
    }
    else {
        await expect(page.getByRole('status', { name: 'Widget selection' })).toHaveText('No selected widget record');
        await expect(page.getByRole('button', { name: 'Toggle secondary signal' })).toHaveAttribute('aria-pressed', 'true');
        await expect(page.getByRole('button', { name: 'Toggle compact widgets' })).toHaveAttribute('aria-pressed', 'false');
    } if (change === 'generation')
        expect(await page.getByText(/Widgets lease:/).textContent()).toBe(old!.replace(/\/g1$/, '/g2')); expect(await page.evaluate(() => (window as any).oldWidgetStyle.isConnected)).toBe(change === 'source'); await expect(page.getByRole('button', { name: change === 'owner' || change === 'generation' ? 'Stable local count 1' : 'Stable local count 0' })).toBeVisible(); });
test('keyboard, bounded paint geometry and narrow review have no external effects; unmount clears leases', async ({ page }) => { const effects: string[] = []; page.on('request', r => { if (!['127.0.0.1:18543', '127.0.0.1:18544'].includes(new URL(r.url()).host) || r.method() !== 'GET')
    effects.push(r.url()); }); await page.reload(); await page.setViewportSize({ width: 390, height: 844 }); await seek(page, 2); const recent = page.getByRole('region', { name: 'Controlled visual widgets' }).locator('[aria-label="Newest recorded first"] button').first(); await recent.focus(); await page.keyboard.press('Enter'); await expect(page.getByRole('status', { name: 'Widget selection' })).toContainText('review ready'); await expect(recent).toBeFocused(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= 390)).toBe(true); const paint = page.locator('.signal-paint [aria-hidden="true"]'); expect(await paint.locator(':scope > div').count()).toBe(6); expect(await paint.locator(':scope > div').evaluateAll(nodes => nodes.map(node => node.getAttribute('title')))).toEqual(['0', '0', '3', '3', '1', '1']); await expect(page.locator('.signal-paint')).toContainText('Primary counts 3'); await expect(page.locator('.signal-paint')).toContainText('Secondary counts 1'); for (const block of await page.locator('.spark-paint [aria-hidden="true"], .signal-paint [aria-hidden="true"]').all()) {
    const r = await block.boundingBox();
    for (const column of await block.locator(':scope > div').all()) {
        await expect(column.locator(':scope > div')).toHaveCount(await block.evaluate(el => el.closest('.signal-paint') ? 18 : 6));
        const end = await column.locator(':scope > div').last().boundingBox();
        expect(end!.y).toBeGreaterThanOrEqual(r!.y);
        const first = await column.locator(':scope > div').first().boundingBox();
        expect(first!.y + first!.height).toBeLessThanOrEqual(r!.y + r!.height + 0.5);
    }
} const bounds = await paint.boundingBox(); expect(bounds!.height).toBeGreaterThan(120); const styles = await page.locator('[aria-label="Known record classes"] svg circle[stroke-dasharray]').first().evaluate(el => ({ stroke: getComputedStyle(el).stroke, info: getComputedStyle(el).getPropertyValue('--color-info').trim() })); expect(styles.info).not.toBe(''); expect(styles.stroke).not.toBe('none'); const cell = await paint.locator(':scope > div > div').first().boundingBox(); expect(cell!.height).toBeLessThan(8); await page.screenshot({ path: '../.scratch/controlled-widgets-narrow.png', fullPage: true }); await page.locator('article[aria-label="Signal counts"]').evaluate(el => el.scrollIntoView({ block: 'start' })); await page.screenshot({ path: '../.scratch/controlled-widgets-narrow-viewport.png', fullPage: false }); await page.getByRole('button', { name: 'Unmount playback consumer' }).click(); await expect(page.getByRole('region', { name: 'Controlled visual widgets' })).toHaveCount(0); await expect(page.locator('link[href*="/plugins/"]')).toHaveCount(0); expect(effects).toEqual([]); });
test('backward seek and reset retire selection and future rows without changing generation CSS', async ({ page }) => { await seek(page, 3); await page.getByRole('button', { name: /source-a: final fixture outcome/ }).click(); await page.getByRole('button', { name: 'Toggle secondary signal' }).click(); await seek(page, 1); const p = page.getByRole('region', { name: 'Controlled visual widgets' }); await expect(p).not.toContainText('final fixture outcome'); await expect(p.locator('tbody tr')).toHaveCount(2); await expect(page.getByRole('status', { name: 'Widget selection' })).toHaveText('No selected widget record'); await expect(page.getByRole('button', { name: 'Toggle secondary signal' })).toHaveAttribute('aria-pressed', 'true'); await page.getByRole('button', { name: 'Reset playback' }).click(); await expect(p.locator('tbody tr')).toHaveCount(1); await expect(p).toContainText('Actual observed peak 0'); await expect(page.locator('link[href*="fake-ops/g1/style.css"]')).toHaveCount(1); });
