import {it,expect,vi} from 'vitest';
import {settingsMetadataProblem} from '@hollis-labs/kit-settings';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createAdminReviewFixture} from '../example/admin-review-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>[{id:'same',ref:{owner:'fake-ops',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createAdminReviewFixture(app),replace(){generation='g2'},withdraw(){available=false}}}
it('canonical declared destinations include current scope and lease; retained declarations navigate and malformed/unknown targets refuse',async()=>{const c=controlled(),f=c.f;f.capture().href();const before=f.destination({page:'status'});expect(before.href).toContain('scope=');expect(before.href).toContain('lease=');f.route(before.href!);expect(f.state.getSnapshot().selection.page).toBe('status');f.capture().appearance('retained-error');f.capture().navigate({page:'settings',groupId:'limits'});expect(f.state.getSnapshot().selection.groupId).toBe('limits');for(const value of ['context-mismatch','unsupported','malformed','contradictory','duplicate','empty'] as const){f.capture().appearance(value);expect(f.allowed({page:'settings',groupId:'appearance'})).toBe(false);expect(f.destination({page:'settings',groupId:'appearance'}).href).toBeUndefined();f.capture().inspect({page:'settings',groupId:'appearance'});expect(f.state.getSnapshot().intent).toBeNull()}f.dispose();await c.app.dispose()});
it('read-only projection omits actions setup and diagnostic observations while authored series satisfies finite declared bounds',async()=>{const c=controlled(),p=c.f.projection();expect(p).not.toHaveProperty('settingsActions');expect(p).not.toHaveProperty('setup');expect(p.observations).not.toHaveProperty('diagnostics');for(const group of p.discovery.manifest!.settings)expect(settingsMetadataProblem(group,p.settings[group.id]!.state!)).toBeUndefined();expect(p.settings.appearance?.state?.values.count.value).toBe(0);expect(p.settings.appearance?.state?.values.enabled.value).toBe(false);const series=p.observations.series.series!;expect(series.points.length).toBeLessThanOrEqual(3);expect(series.points.every(p=>Date.parse(p.at)>=Date.parse(series.requested.from)&&Date.parse(p.at)<=Date.parse(series.requested.to))).toBe(true);c.f.dispose();await c.app.dispose()});
it('stale captured callbacks and hrefs refuse real generation/owner/source/manifest/selection changes without notification',async()=>{for(const change of ['generation','owner','source','manifest','group'] as const){const c=controlled(),f=c.f;f.capture().href();const href=f.destination({page:'status'}).href!,old=f.capture();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else f.capture()[change]();old.navigate({page:'status'});f.route(href);expect(f.state.getSnapshot().selection.page).not.toBe('status');f.dispose();await c.app.dispose()}});
it('ignored-abort held commit alone rechecks generation/currentness and closes local inspection on all retirements',async()=>{for(const change of ['generation','owner','source','manifest','group','unmount'] as const){const c=controlled(),f=c.f;f.capture().inspect({page:'settings',groupId:'appearance'});f.capture().open(true);if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else if(change==='unmount')f.dispose();else f.capture()[change]();f.release();await Promise.resolve();expect(f.state.getSnapshot().intent).toBeNull();expect(f.state.getSnapshot().open).toBe(false);expect(f.state.getSnapshot().output).not.toContain('Inspected local destination');f.dispose();await c.app.dispose()}});
it('unknown page/group recovery and effective displayed candidate plus close retirement/stale-close guard',async()=>{const c=controlled(),f=c.f;f.capture().appearance('unknown-page');f.capture().inspect({page:'settings',groupId:'appearance'});expect(f.state.getSnapshot().intent?.from.page).toBe('unknown');f.capture().open(true);const old=f.capture();f.capture().open(false);f.capture().navigate({page:'settings',groupId:'appearance'});expect(f.state.getSnapshot().appearance).toBe('ready');f.capture().inspect({page:'settings',groupId:'appearance'});f.capture().open(true);old.open(false);expect(f.state.getSnapshot().open).toBe(true);f.release();await Promise.resolve();expect(f.state.getSnapshot().output).toContain('supplied records unchanged');f.dispose();f.dispose();await c.app.dispose()});
