import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createContributionSwitcher,switcherValue} from '../example/contribution-switcher-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',alive=true;const views=()=>[{id:'detail',label:'Actual detail',ref:{hostInstance:'host',owner:'fake-ops',generation,kind:'panel',key:'detail'},region:'operations.detail',representation:'component',availability:'available'},{id:'stable',label:'Actual stable',ref:{hostInstance:'host',owner:'stable-plugin',generation:'g1',kind:'widget',key:'stable'},region:'operations.summary',representation:'component',availability:'available'},{id:'action',label:'Action metadata',ref:{hostInstance:'host',owner:'fake-ops',generation,kind:'slot',key:'simulate'},region:'operations.toolbar',representation:'declarative',availability:'available'}] as ContributionView[];vi.spyOn(app.runtime,'getSnapshot').mockImplementation(()=>({version:1,hostInstance:'host',revision:1,isolationMode:'main-origin',views:views(),refusals:[]}));vi.spyOn(app.runtime,'isCurrent').mockImplementation(view=>view.ref.owner==='stable-plugin'||alive);vi.spyOn(app,'select').mockImplementation(region=>views().filter(view=>view.region===region&&app.layouts.get(region)?.getSnapshot().visibility[view.id]!==false));return{app,f:createContributionSwitcher(app),views,replace(){generation='g2'},withdraw(){alive=false}}}
function activate(c:ReturnType<typeof controlled>,id='detail'){const value=switcherValue(c.views().find(v=>v.id===id)!),callback=c.f.capture();callback.highlight(value);callback.activate(value);return value}
it('actual finite view identities include currenthost/ref/generation, native highlight then onSelect shares querylease; disabledmetadata cannotactivate',async()=>{const c=controlled(),f=c.f,old=f.capture();const value=switcherValue(c.views()[0]);old.highlight(value);old.activate(value);expect(f.selected()?.id).toBe('detail');const metadata=switcherValue(c.views()[2]);f.capture().highlight(metadata);f.capture().activate(metadata);expect(f.selected()?.id).toBe('detail');c.replace();f.refresh();expect(f.selected()).toBeUndefined();expect(switcherValue(c.views()[0])).not.toBe(value);old.highlight(value);old.activate(value);expect(f.selected()).toBeUndefined();f.capture().query('newquery');old.query('stalequery');expect(f.state.getSnapshot().query).toBe('newquery');f.dispose();await c.app.dispose()});
it('ignoredabort/capturedcallbacks reread current owner generation frame source query highlight activatedselection phase close consumer',async()=>{for(const change of ['generation','owner','frame','source','query','highlight','selection','phase','close','unmount']){const c=controlled(),f=c.f,value=activate(c);const old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='frame')c.app.seek(2);else if(change==='source')c.app.retireSource();else if(change==='query')f.capture().query('different');else if(change==='highlight')f.capture().highlight(switcherValue(c.views()[1]));else if(change==='selection')activate(c,'stable');else if(change==='phase')f.capture().phase('denied');else if(change==='close')f.capture().close();else f.dispose();f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');old.activate(value);expect(f.selected()?.id).not.toBe('detail');f.dispose();await c.app.dispose()}});
it('actual layout visibility observer immediately retires selected slot and held ticket, cleanup stops subscription',async()=>{const c=controlled(),f=c.f;activate(c);f.capture().hold();const old=f.capture(),value=switcherValue(c.views()[0]),layout=c.app.layouts.get('operations.detail')!;layout.save({order:[],visibility:{detail:false}});expect(f.state.getSnapshot().selected).toBe(null);expect(f.state.getSnapshot().busy).toBe(false);expect(f.eligible(c.views()[0])).toBe(false);f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');old.activate(value);expect(f.selected()).toBeUndefined();layout.save({order:[],visibility:{detail:true}});activate(c);f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).toContain('registry unchanged');f.dispose();f.dispose();layout.save({order:[],visibility:{detail:false}});expect(f.state.getSnapshot().selected).toBe(null);await c.app.dispose()});
it('unrelated actualowner replacement preserves selectedstable identity and currentheld inspection',async()=>{const c=controlled(),f=c.f;const value=activate(c,'stable');f.capture().hold();c.replace();f.release();await Promise.resolve();expect(f.selected()?.id).toBe('stable');expect(f.state.getSnapshot().selected).toBe(value);expect(f.state.getSnapshot().outcome).toContain('stable-plugin/stable generation g1 locally; registry unchanged');f.dispose();await c.app.dispose()});
