import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createContributionWorkbench} from '../example/contribution-workbench-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let gen='g1',current=true;const row=()=>({id:'panel:fake-ops/detail',label:'Fixture detail',ref:{owner:'fake-ops',kind:'panel',key:'detail',hostInstance:'h',generation:gen},region:'operations.detail',representation:'component',availability:'available',widget:false,props:{}} as ContributionView);vi.spyOn(app.runtime,'getSnapshot').mockImplementation(()=>({version:1,hostInstance:'h',revision:1,isolationMode:'main-origin',views:[row()],refusals:[]}));vi.spyOn(app,'select').mockImplementation(()=>current?[row()]:[]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>current);return{app,f:createContributionWorkbench(app),replace(){gen='g2'},withdraw(){current=false}}}
it('actual readonly catalogue filters and selected preview use declared eligible regions; no arbitrary owner or target',async()=>{const c=controlled(),f=c.f;f.capture().owner('unknown');expect(f.state.getSnapshot().owner).toBe('all');f.capture().select('unknown');expect(f.selected()).toBeUndefined();f.capture().select('panel:fake-ops/detail');expect(f.eligible(f.selected()!)).toBe(true);expect(f.eligible({...f.selected()!,ref:{...f.selected()!.ref,kind:'future.widget'}})).toBe(false);f.capture().preview(true);expect(f.state.getSnapshot().preview).toBe(true);f.capture().query('nomatch');expect(f.filtered()).toHaveLength(0);expect(f.selected()).toBeUndefined();f.dispose();await c.app.dispose()});
it('immediate currentness and ignored-abort commits re-read exact generation/frame/selection/filter/preview/unmount even without subscription',async()=>{for(const change of ['generation','owner','frame','filter','selection','preview','unmount']){const c=controlled(),f=c.f;f.capture().select('panel:fake-ops/detail');f.capture().preview(true);const old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='frame')c.app.seek(2);else if(change==='filter')f.capture().query('other');else if(change==='selection')f.capture().select('panel:fake-ops/detail');else if(change==='preview')f.capture().preview(false);else f.dispose();old.preview(true);f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');f.dispose();await c.app.dispose()}});
it('finite readonly inspection completes without registry mutation while repeated disposal is safe',async()=>{const c=controlled(),f=c.f;f.capture().select('panel:fake-ops/detail');f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).toContain('registry unchanged');expect(c.app.runtime.getSnapshot().views[0].ref.generation).toBe('g1');f.dispose();f.dispose();await c.app.dispose()});

it('hidden declared slot closes preview and refuses captured mount/held commit without layout mutation UI',async()=>{const c=controlled(),f=c.f;f.capture().select('panel:fake-ops/detail');f.capture().preview(true);const old=f.capture();old.hold();vi.mocked(c.app.select).mockReturnValue([]);f.release();await Promise.resolve();expect(f.state.getSnapshot().preview).toBe(false);expect(f.state.getSnapshot().outcome).not.toContain('Inspected');old.preview(true);expect(f.state.getSnapshot().preview).toBe(false);f.dispose();await c.app.dispose()});
