import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createDeveloperEvidenceFixture,developerFiles,developerTests} from '../example/developer-evidence-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>[{id:'same',ref:{owner:'fake-ops',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createDeveloperEvidenceFixture(app),replace(){generation='g2'},withdraw(){available=false}}}
it('authored finite ledger has explicit running/skipped denominator and zero versus missing durations',()=>{expect(developerTests).toHaveLength(4);expect(developerTests.filter(t=>t.status==='passed'||t.status==='failed')).toHaveLength(2);expect(developerTests[0].duration).toBe(0);expect(developerTests[2].duration).toBeUndefined();expect(developerTests.every(t=>t.duration===undefined||Number.isFinite(t.duration)&&t.duration>=0)).toBe(true);expect(developerFiles['src/empty.ts']).toBe('')});
it('native file/frame mapping admits only declared current safe line/column; unknown parsed location visible refusal',async()=>{const c=controlled(),f=c.f;f.capture().file('src/verify.ts',2,1);expect(f.state.getSnapshot().line).toBe(2);for(const [path,line,column] of [['unknown.ts',1,1],['src/verify.ts',0,1],['src/verify.ts',9,1],['src/verify.ts',2,999]] as const){f.capture().file(path,line,column);expect(f.state.getSnapshot().path).toBe('src/verify.ts');expect(f.state.getSnapshot().line).toBe(2);expect(f.state.getSnapshot().output).toMatch(/unavailable/)}f.capture().file('src/empty.ts');expect(f.state.getSnapshot().path).toBe('src/empty.ts');f.dispose();await c.app.dispose()});
it('captured selection and ignored-abort commit alone recheck actual ref generation/currentness/frame/selection/disclosure',async()=>{for(const change of ['generation','owner','source','cutoff','selection','disclosure','unmount'] as const){const c=controlled(),f=c.f,old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else if(change==='cutoff')c.app.seek(2);else if(change==='selection')f.capture().select('zero');else if(change==='disclosure')f.capture().suite(false);else f.dispose();old.select('skip');f.release();await Promise.resolve();expect(f.state.getSnapshot().selected).not.toBe('skip');expect(f.state.getSnapshot().output).not.toContain('Inspected supplied');f.dispose();await c.app.dispose()}});
it('unknown/locked/unavailable phases withhold review callbacks; latest current held candidate only inspects immutable evidence',async()=>{const c=controlled(),f=c.f;for(const phase of ['missing','loading','error','denied','unknown','locked','empty'] as const){f.capture().phase(phase);f.capture().select('skip');f.capture().hold();expect(f.state.getSnapshot().selected).toBe('failure');expect(f.state.getSnapshot().busy).toBe(false);f.capture().phase('ready')}f.capture().select('zero');f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().output).toContain('zero/src/verify.ts:2 locally; evidence unchanged');expect(developerTests[0].status).toBe('passed');f.dispose();f.dispose();await c.app.dispose()});
