import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createDirectoryReview,directoryProfiles,directorySnapshotClock} from '../example/directory-review-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>app.layouts.get('operations.detail')!.getSnapshot().visibility.same===false?[]:[{id:'same',ref:{owner:'fake-ops',kind:'panel',key:'detail',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createDirectoryReview(app),replace(){generation='g2'},withdraw(){available=false}}}
it('authored fullsnapshot independentcutoff uses finite profiles and distinct zero/missing relationships',async()=>{const c=controlled(),f=c.f;expect(directoryProfiles[1].roles).toEqual([]);expect(directoryProfiles[2].roles).toEqual(['missing-role']);expect(directorySnapshotClock).toBe('2026-10-05T10:00:00.000Z');f.capture().profile('mira');expect(f.selected().id).toBe('mira');c.app.seek(3);f.refresh();expect(f.selected().id).toBe('ada');expect(directoryProfiles).toHaveLength(3);f.capture().profile('unknown');f.capture().tab('unknown');f.capture().tab({toString:()=> 'relationships'});expect(f.state.getSnapshot().tab).toBe('profile');f.dispose();await c.app.dispose()});
it('captured callbacks and ignoredabort producer reread actualowner/generation/frame/profile/tab/popup/phase/consumer without subscription',async()=>{for(const change of ['generation','owner','source','cutoff','profile','tab','popup','phase','unmount']){const c=controlled(),f=c.f;f.capture().popup(true);const old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else if(change==='cutoff')c.app.seek(2);else if(change==='profile')f.capture().profile('mira');else if(change==='tab')f.capture().tab('relationships');else if(change==='popup')f.capture().popup(true);else if(change==='phase')f.capture().phase('denied');else f.dispose();old.profile('sol');f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');if(!['tab','profile','popup'].includes(change))expect(f.state.getSnapshot().popup).toBe(false);expect(f.state.getSnapshot().profile).not.toBe('sol');f.dispose();await c.app.dispose()}});
it('popup close-origin token finite current profile/tab lease; close/reopen and retirement cannot restore old trigger or commit',async()=>{const c=controlled(),f=c.f;for(const transition of ['profile','tab','phase','reopen'] as const){f.capture().phase('ready');f.capture().popup(true);const old=f.state.getSnapshot();f.capture().popup(false);expect(f.canRestore(old.identity,old.epoch)).toBe(true);if(transition==='profile')f.capture().profile('sol');else if(transition==='tab')f.capture().tab('relationships');else if(transition==='phase')f.capture().phase('unknown');else f.capture().popup(true);expect(f.canRestore(old.identity,old.epoch)).toBe(false)}f.capture().popup(false);f.capture().phase('ready');f.capture().popup(true);const outside=f.state.getSnapshot();f.capture().popup(false,false);expect(f.canRestore(outside.identity,outside.epoch)).toBe(false);f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).toContain('snapshot unchanged');f.dispose();f.dispose();await c.app.dispose()});

it('actual Detail layout save synchronously retires visible scope popup and held ticket before any callback or release refresh',async()=>{const c=controlled(),f=c.f;f.capture().popup(true);f.capture().hold();const old=f.capture(),layout=c.app.layouts.get('operations.detail')!;layout.save({order:[],visibility:{same:false}});expect(f.state.getSnapshot().available).toBe(false);expect(f.state.getSnapshot().popup).toBe(false);expect(f.state.getSnapshot().busy).toBe(false);f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');old.popup(true);expect(f.state.getSnapshot().popup).toBe(false);layout.save({order:[],visibility:{same:true}});expect(f.state.getSnapshot().available).toBe(true);expect(f.state.getSnapshot().profile).toBe('ada');f.dispose();layout.save({order:[],visibility:{same:false}});expect(f.state.getSnapshot().popup).toBe(false);await c.app.dispose()});
