import {test,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture,playbackBoundaries} from '../example/playback-fixture.js';
import {authoredLedger,ledgerPrefix,rawLedgerValue,createEventLedger} from '../example/event-ledger-fixture.js';
function controlled(){const app=createPlaybackFixture('ledger-context');let generation='g1',alive=true;vi.spyOn(app,'select').mockImplementation(region=>{const view:ContributionView={id:'detail',ref:{hostInstance:'host',owner:'fake-ops',generation,kind:'panel',key:'detail'},region,representation:'component',availability:'available',label:'Actual Detail',widget:false,status:'ready',props:{}};return region==='operations.detail'&&alive&&app.layouts.get(region)?.getSnapshot().visibility.detail!==false?[view]:[]});vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>alive);return{app,f:createEventLedger(app),replace(){generation='g2'},withdraw(){alive=false}}}
function held(c:ReturnType<typeof controlled>,id='authored-0-0'){c.f.capture().select(id);c.f.capture().hold()}
test('authored UTC prefix neverfuture and raw0/null/absence/unknown distinct with exact supplied missingreference',()=>{expect(authoredLedger).toHaveLength(24);playbackBoundaries.forEach((cutoff,i)=>{const rows=ledgerPrefix(cutoff);expect(rows).toHaveLength((i+1)*6);expect(rows.every(row=>row.at<=cutoff)).toBe(true)});expect(rawLedgerValue(0)).toBe('0');expect(rawLedgerValue(null)).toBe('null (Unknown)');expect(rawLedgerValue(undefined)).toBe('undefined (absent; Unknown)');expect(rawLedgerValue('future-tag')).toContain('unknown raw tag');expect(authoredLedger[5].reference).toBeUndefined();expect(authoredLedger[4].message).toContain('<script>')});
test('old captured callback and ignoredabort producer re-read exact actualref/frame/source/query/sort/selection/phase/close/consumer beforecommit',async()=>{for(const change of ['generation','owner','frame','source','query','sort','selection','phase','close','unmount']){const c=controlled();held(c);const old=c.f.capture();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='frame')c.app.seek(2);else if(change==='source')c.app.retireSource();else if(change==='query')c.f.capture().query('log');else if(change==='sort')c.f.capture().sort('descending');else if(change==='selection')c.f.capture().select('authored-0-1');else if(change==='phase')c.f.capture().phase('denied');else if(change==='close')c.f.capture().clear();else c.f.dispose();c.f.release();await Promise.resolve();expect(c.f.state.getSnapshot().outcome).not.toContain('Inspected');old.select('authored-0-0');expect(c.f.state.getSnapshot().selected).not.toBe('authored-0-0');c.f.dispose();await c.app.dispose()}});
test('actual layout listener immediatelywithholds selected/held evidence and disposedownedobserver staysinactive',async()=>{const c=controlled();held(c);const layout=c.app.layouts.get('operations.detail')!;layout.save({order:[],visibility:{detail:false}});expect(c.f.state.getSnapshot().available).toBe(false);expect(c.f.state.getSnapshot().selected).toBe(null);expect(c.f.admitted()).toEqual([]);c.f.release();await Promise.resolve();expect(c.f.state.getSnapshot().outcome).not.toContain('Inspected');c.f.dispose();c.f.dispose();layout.save({order:[],visibility:{detail:true}});expect(c.f.state.getSnapshot().available).toBe(false);await c.app.dispose()});
test('native filter/sort projection honestempty/blocked counts and currentowner inspection complete withoutmutation',async()=>{const c=controlled();c.f.capture().query('authored-0-0');expect(c.f.rows()).toHaveLength(1);c.f.capture().query('no-match');expect(c.f.admitted()).toHaveLength(6);expect(c.f.rows()).toEqual([]);c.f.capture().query('');c.f.capture().sort('descending');expect(c.f.rows()[0].id).toBe('authored-0-5');held(c);c.f.release();await Promise.resolve();expect(c.f.state.getSnapshot().outcome).toContain('authored ledger and registry unchanged');expect(authoredLedger).toHaveLength(24);c.f.capture().phase('empty');expect(c.f.present()).toBe(true);expect(c.f.admitted()).toEqual([]);c.f.capture().phase('denied');expect(c.f.present()).toBe(false);c.f.dispose();await c.app.dispose()});
