import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createExplorerReviewFixture} from '../example/explorer-review-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>[{id:'same',ref:{owner:'fake-ops',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createExplorerReviewFixture(app),replace(){generation='g2'},withdraw(){available=false}}}
it('bounded authored prefix joins only receipts at or before cutoff; null zero and absent stay distinct',async()=>{const c=controlled();for(let i=0;i<4;i++){c.app.seek(i);c.f.refresh();const s=c.f.state.getSnapshot();expect(s.admitted).toHaveLength((i+1)*8);expect(s.admitted.filter(r=>r.receipt)).toHaveLength(i<2?0:i===2?8:16);for(const row of s.admitted){expect(Date.parse(row.queuedAt)).toBeLessThanOrEqual(c.app.frame.getSnapshot().cutoff);if(row.receipt)expect(Date.parse(row.receipt.observedAt)).toBeLessThanOrEqual(c.app.frame.getSnapshot().cutoff)}}c.f.capture().evidence('zero');expect(c.f.state.getSnapshot().rows.every(row=>row.units===0&&row.receipt!==null)).toBe(true);expect(c.f.state.getSnapshot().rows).toHaveLength(6);c.f.capture().evidence('unknown');expect(c.f.state.getSnapshot().rows).toHaveLength(21);c.f.dispose();await c.app.dispose()});
it('finite current owner/status/evidence/query facets intersect and reject unsupported values',async()=>{const c=controlled();c.app.seek(3);c.f.refresh();c.f.capture().owner('fixture-alpha');c.f.capture().status('completed');c.f.capture().evidence('reported');expect(c.f.state.getSnapshot().rows).toHaveLength(8);c.f.capture().query('03');expect(c.f.state.getSnapshot().rows.map(row=>row.id)).toEqual(['local-run-03']);c.f.capture().owner('missing');expect(c.f.state.getSnapshot().owner).toBe('fixture-alpha');c.f.capture().evidence('unsupported' as never);expect(c.f.state.getSnapshot().evidence).toBe('reported');c.f.capture().query('nothing');expect(c.f.state.getSnapshot().rows).toHaveLength(0);expect(c.f.state.getSnapshot().admitted).toHaveLength(32);c.f.capture().clear();expect(c.f.state.getSnapshot().rows).toHaveLength(32);c.f.dispose();await c.app.dispose()});
it('selection and inspection retire on facets while density retains the current projection references',async()=>{const c=controlled(),f=c.f,row=f.state.getSnapshot().rows[0];f.capture().selected([row.id]);f.capture().open(row.id,row);f.capture().density();expect(f.state.getSnapshot().record).toBe(row);expect(f.state.getSnapshot().selected).toEqual([row.id]);f.capture().query('02');expect(f.state.getSnapshot().record).toBeNull();expect(f.state.getSnapshot().selected).toEqual([]);f.dispose();await c.app.dispose()});
it('captured callbacks and ignored-abort commit reread actual scope without subscription',async()=>{for(const change of ['generation','owner','source','cutoff','filter','phase','close','unmount'] as const){const c=controlled(),f=c.f,row=f.state.getSnapshot().rows[0];f.capture().open(row.id,row);const old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else if(change==='cutoff')c.app.seek(2);else if(change==='filter')f.capture().query('02');else if(change==='phase')f.capture().phase('error');else if(change==='close')f.capture().close();else f.dispose();old.open(row.id,row);f.release();await Promise.resolve();expect(f.state.getSnapshot().record).toBeNull();expect(f.state.getSnapshot().result).not.toContain('Inspected');f.dispose();await c.app.dispose()}});
it('absent loading error denied and successful empty remain distinct; only current inspected row can finish',async()=>{const c=controlled(),f=c.f;for(const phase of ['absent','loading','error','denied','empty'] as const){f.capture().phase(phase);expect(f.state.getSnapshot().phase).toBe(phase);expect(f.state.getSnapshot().rows).toEqual([]);f.capture().phase('ready')}const row=f.state.getSnapshot().rows[0];f.capture().open(row.id,{...row});expect(f.state.getSnapshot().record).toBeNull();f.capture().open(row.id,row);f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().result).toContain('supplied evidence unchanged');f.dispose();f.dispose();await c.app.dispose()});
