import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createObservationReviewFixture,observationReceipt} from '../example/observation-review-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>[{id:'same',ref:{owner:'fake-ops',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createObservationReviewFixture(app),replace(){generation='g2'},withdraw(){available=false}}}
it('authored sample chronology and finite resource bounds retain receipt across clock and local inspection',async()=>{const c=controlled(),f=c.f,initial=f.props();expect(initial.series.points.every(p=>Date.parse(p.at)<=observationReceipt)).toBe(true);expect(initial.series.points.length).toBeLessThanOrEqual(initial.series.bounds.maxPoints);expect(Date.parse(initial.series.requested.to)-Date.parse(initial.series.requested.from)).toBeLessThanOrEqual(initial.series.bounds.maxWindowSeconds*1000);f.capture().retry();f.release();await Promise.resolve();expect(f.state.getSnapshot().output).toContain('receipt unchanged');expect(f.props().observation.observedAt).toBe(initial.observation.observedAt);f.capture().clock();expect(f.props().observation.observedAt).toBe(initial.observation.observedAt);f.dispose();await c.app.dispose()});
it('zero/null/nonfinite and all units/kinds remain distinct; series preserves null and nonuniform timestamp',async()=>{const c=controlled(),p=c.f.props();expect(p.stats.rows.map(r=>r.value)).toEqual([0,null,NaN,12,.25,25]);expect(p.stats.rows.map(r=>r.unit)).toEqual(['count','bytes','seconds','milliseconds','ratio','percent']);expect(p.series.points.map(p=>p.value)).toEqual([0,4,null,2,1]);expect(Date.parse(p.series.points[1].at)-Date.parse(p.series.points[0].at)).toBe(500);c.f.dispose();await c.app.dispose()});
it('immediate and ignored-abort commit refresh actual same-id generation/currentness without observer notifications',async()=>{for(const change of ['generation','owner','source','unmount'] as const)for(const check of ['immediate','commit']){const c=controlled(),f=c.f,old=f.capture();f.capture().retry();if(change==='generation')c.replace();else if(change==='owner')c.withdraw();else if(change==='source')c.app.retireSource();else f.dispose();if(check==='immediate')old.retry();f.release();await Promise.resolve();expect(f.state.getSnapshot().intent).toBeNull();expect(f.state.getSnapshot().output).not.toContain('Inspected retry');f.dispose();await c.app.dispose()}});
it('resource receipt appearance clock and close retire tickets, stale close cannot close fresh inspection',async()=>{for(const transition of ['resource','receipt','clock','appearance','close'] as const){const c=controlled(),f=c.f;f.capture().retry();f.capture().open(true);const old=f.capture();if(transition==='appearance')f.capture().appearance('ready');else if(transition==='close')f.capture().open(false);else f.capture()[transition]();f.release();await Promise.resolve();expect(f.state.getSnapshot().intent).toBeNull();if(transition==='close'){f.capture().retry();f.capture().open(true);old.open(false);expect(f.state.getSnapshot().open).toBe(true)}f.dispose();f.dispose();await c.app.dispose()}});
it('rendered retry capability and admission share finite policy; all scenario timestamps stay valid for chart',async()=>{const c=controlled(),f=c.f;for(const value of ['ready','refreshing','unsupported','paused','stale','invalid-receipt','initial-loading'] as const){f.capture().appearance(value);const p=f.props();expect(p.observation.onRetry).toBeUndefined();f.capture().retry();expect(f.state.getSnapshot().intent).toBeNull();expect(p.series.points.every(point=>Number.isFinite(Date.parse(point.at))&&Date.parse(point.at)>=Date.parse(p.series.requested.from)&&Date.parse(point.at)<=Date.parse(p.series.requested.to))).toBe(true);expect(p.series.points.length).toBeLessThanOrEqual(p.series.bounds.maxPoints);expect(p.series.requested.limit).toBeLessThanOrEqual(p.series.bounds.maxPoints);expect(Date.parse(p.series.requested.to)-Date.parse(p.series.requested.from)).toBeLessThanOrEqual(p.series.bounds.maxWindowSeconds*1000)}f.capture().appearance('initial-error');expect(f.props().observation.observedAt).toBeUndefined();f.capture().retry();expect(f.state.getSnapshot().intent?.receipt).toBeNull();f.capture().open(false);expect(f.props().observation.onRetry).toBeTypeOf('function');f.dispose();await c.app.dispose()});
