import {it,expect,vi} from 'vitest';
import type {ContributionView} from '@hollis-labs/plugin-host-ui';
import {createPlaybackFixture} from '../example/playback-fixture.js';
import {createOpsMetrics,metricProjection,rawMetric,displayMetric} from '../example/ops-metrics-fixture.js';
function controlled(){const app=createPlaybackFixture('a');let generation='g1',available=true;vi.spyOn(app,'select').mockImplementation(()=>app.layouts.get('operations.detail')!.getSnapshot().visibility.same===false?[]:[{id:'same',ref:{owner:'fake-ops',kind:'panel',key:'detail',hostInstance:'host',generation}} as ContributionView]);vi.spyOn(app.runtime,'isCurrent').mockImplementation(()=>available);return{app,f:createOpsMetrics(app),replace(){generation='g2'},withdraw(){available=false}}}
it('authored finiteprefix preserves zero/null/missing/nonfinite/status operands separately from formatted output',()=>{const early=metricProjection(0,'usage'),late=metricProjection(3,'usage');expect(early[0].value).toBe(null);expect(early[0].status).toBeUndefined();expect(early[1].value).toBe(0);expect(rawMetric(early[1].value)).toBe('0');expect(displayMetric(early[1])).toBe('$0.0000');expect(displayMetric(late[1])).toBe('$0.0000');expect(rawMetric(late[1].value)).toBe('1.9e-7');expect(rawMetric(late[2].value)).toBe('undefined (Unknown)');expect(rawMetric(late[3].value)).toBe('NaN (invalid; Unknown)');expect(displayMetric(late[3])).toBe('Unknown');expect(late[3].status).toBe('future-state')});
it('samecurrentowner cutoff preserves selectedtab/currentmetric but retires old producer and futuremetric selection',async()=>{const c=controlled(),f=c.f;f.capture().tab('usage');c.app.seek(3);f.refresh();expect(f.state.getSnapshot().tab).toBe('usage');f.capture().select('tokens');f.capture().hold();const old=f.capture();c.app.seek(2);f.release();await Promise.resolve();expect(f.state.getSnapshot().tab).toBe('usage');expect(f.state.getSnapshot().selected).toBe('tokens');expect(f.state.getSnapshot().busy).toBe(false);expect(f.state.getSnapshot().outcome).toBe('No local metric inspection');old.select('cost');expect(f.state.getSnapshot().selected).toBe('tokens');c.app.seek(3);f.refresh();f.capture().select('invalid');c.app.seek(0);f.refresh();expect(f.state.getSnapshot().selected).toBe(null);expect(f.state.getSnapshot().tab).toBe('usage');expect(f.rows().some(row=>row.id==='invalid')).toBe(false);f.capture().hold();expect(f.state.getSnapshot().busy).toBe(false);f.dispose();await c.app.dispose()});
it('callbacks/ignoredabort reread current generation source owner phase tab selection and consumer without observer delivery',async()=>{for(const change of ['generation','source','owner','phase','tab','selection','close','unmount']){const c=controlled(),f=c.f;f.capture().select('starts');const old=f.capture();old.hold();if(change==='generation')c.replace();else if(change==='source')c.app.retireSource();else if(change==='owner')c.withdraw();else if(change==='phase')f.capture().phase('denied');else if(change==='tab')f.capture().tab('usage');else if(change==='selection')f.capture().select('failures');else if(change==='close')f.capture().clear();else f.dispose();old.select('latency');f.release();await Promise.resolve();expect(f.state.getSnapshot().selected).not.toBe('latency');expect(f.state.getSnapshot().outcome).not.toContain('Inspected');f.dispose();await c.app.dispose()}});
it('actualvisibleDetail layout listener immediately retires selected current scope; idempotent cleanup and current local inspection',async()=>{const c=controlled(),f=c.f;f.capture().tab('mission');f.capture().select('tasks');f.capture().hold();const layout=c.app.layouts.get('operations.detail')!;layout.save({order:[],visibility:{same:false}});expect(f.state.getSnapshot().available).toBe(false);expect(f.state.getSnapshot().selected).toBe(null);expect(f.state.getSnapshot().busy).toBe(false);f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).not.toContain('Inspected');layout.save({order:[],visibility:{same:true}});expect(f.state.getSnapshot().tab).toBe('activity');f.capture().select('starts');f.capture().hold();f.release();await Promise.resolve();expect(f.state.getSnapshot().outcome).toContain('raw 0 count; authored snapshot unchanged');f.dispose();f.dispose();layout.save({order:[],visibility:{same:false}});expect(f.state.getSnapshot().available).toBe(false);await c.app.dispose()});
