import { it, expect } from 'vitest';
import { createOverlayFixture } from '../example/overlay-fixture.js';
const flush = async () => { await Promise.resolve(); await Promise.resolve(); };
it('guards native invalid/busy submits, retains rejected and accepted local drafts', async () => {
    const app = createOverlayFixture(() => ({ identity: 'context/source/frame/host/detail/g1', available: true }));
    app.capture().open();
    app.submit(app.capture());
    expect(app.pending()).toHaveLength(0);
    app.capture().change('review');
    app.submit(app.capture());
    app.submit(app.capture());
    expect(app.pending()).toHaveLength(1);
    app.release(false);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: 'review', busy: false, outcome: 'Preview rejected; draft retained' });
    app.submit(app.capture());
    app.release(true);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: 'review', outcome: 'Local preview: review' });
    app.dispose();
});
it('re-reads scope before commit and refuses stale captured callbacks without subscription notification', async () => {
    let scope = { identity: 'context/source/frame/host/detail/g1', available: true };
    const app = createOverlayFixture(() => scope);
    app.capture().open();
    app.capture().change('old');
    const stale = app.capture();
    app.submit(stale);
    scope = { ...scope, identity: 'context/source/frame/host/detail/g2' };
    app.release(true);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: '', outcome: '', form: false, busy: false });
    stale.open();
    app.submit(stale);
    expect(app.pending()).toHaveLength(0);
    app.capture().open();
    app.capture().change('new');
    app.submit(app.capture());
    scope = { ...scope, available: false };
    app.release(true);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: '', outcome: '', available: false });
    app.dispose();
});
it('busy close cancels preview and confirmation; draft changes and disposal retire captured callbacks', async () => {
    const app = createOverlayFixture(() => ({ identity: 'context/source/frame/host/detail/g1', available: true }));
    app.capture().open();
    app.capture().change('draft');
    app.submit(app.capture());
    const signal = app.pending()[0];
    app.capture().close();
    expect(signal.aborted).toBe(true);
    app.release(true);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: 'draft', outcome: '', form: false });
    app.capture().confirm();
    app.confirm(app.capture());
    app.capture().close();
    app.release(true);
    await flush();
    expect(app.state.getSnapshot()).toMatchObject({ draft: 'draft', confirm: false, outcome: '' });
    const old = app.capture();
    app.capture().change('changed');
    old.open();
    expect(app.state.getSnapshot().form).toBe(false);
    app.capture().open();
    app.submit(app.capture());
    const saved = app.capture();
    app.dispose();
    app.dispose();
    app.release(true);
    await flush();
    saved.open();
    expect(app.state.getSnapshot()).toMatchObject({ draft: '', outcome: '', form: false });
});
