import { describe, it, expect, vi } from 'vitest';
import type { ContributionView } from '@hollis-labs/plugin-host-ui';
import { settingsWizardEvaluation } from '@hollis-labs/kit-settings';
import { createPlaybackFixture } from '../example/playback-fixture.js';
import { createSettingsReviewFixture, settingsReviewGroups } from '../example/settings-review-fixture.js';
function controlled() { const app = createPlaybackFixture('a'); let generation = 'g1', available = true; vi.spyOn(app, 'select').mockImplementation(() => [{ id: 'same', ref: { owner: 'fake-ops', hostInstance: 'host', generation } } as ContributionView]); vi.spyOn(app.runtime, 'isCurrent').mockImplementation(() => available); const fixture = createSettingsReviewFixture(app); return { app, fixture, replace() { generation = 'g2'; }, withdraw() { available = false; } }; }
function edit(f: ReturnType<typeof createSettingsReviewFixture>) { f.capture().draft('display', { title: { kind: 'value', value: 'Local reviewed title' } }); }
function review(f: ReturnType<typeof createSettingsReviewFixture>) { f.capture().step(2); return settingsWizardEvaluation(settingsReviewGroups, f.state.getSnapshot().states).plan; }
describe('private settings review policy', () => {
    it('uses actual kit validation, holds plans without changing values/drafts, and never stages secret/locked fields', async () => { const { app, fixture: f } = controlled(); f.capture().draft('display', { secret: { kind: 'value', value: 'forbidden' } }); expect(f.state.getSnapshot().states.display.draft).toEqual({}); f.capture().draft('display', { count: { kind: 'text', text: '-' } }); f.capture().preview(); expect(f.state.getSnapshot().busy).toBe(false); expect(f.state.getSnapshot().output).toContain('No valid'); edit(f); const plan = review(f); f.capture().complete(plan); expect(f.state.getSnapshot().busy).toBe(true); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual(plan); expect(f.state.getSnapshot().states.display.values.title.value).toBe('Authored fixture'); expect(f.state.getSnapshot().states.display.draft.title).toEqual({ kind: 'value', value: 'Local reviewed title' }); expect(f.state.getSnapshot().states.display.apply?.restartRequired).toBe(true); f.dispose(); await app.dispose(); });
    it('captured completion requires current wizard review step and mode; Back/edit/source/generation retire held outcomes', async () => { const c = controlled(), f = c.fixture; edit(f); const plan = review(f), old = f.capture(); f.capture().step(1); old.complete(plan); expect(f.state.getSnapshot().busy).toBe(false); f.capture().complete(plan); expect(f.state.getSnapshot().busy).toBe(false); f.capture().step(2); f.capture().complete(plan); f.capture().mode('renderer'); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual([]); f.capture().mode('wizard'); f.capture().complete(plan); expect(f.state.getSnapshot().busy).toBe(true); c.replace(); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().step).toBe(0); expect(f.state.getSnapshot().states.display.draft).toEqual({}); edit(f); f.capture().preview(); c.app.retireSource(); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual([]); c.withdraw(); f.capture().preview(); expect(f.state.getSnapshot().available).toBe(false); f.dispose(); await c.app.dispose(); });
    it('re-evaluates current plan before held commit even without observer notification; disposal fences ignoring producer', async () => { const { app, fixture: f } = controlled(); edit(f); const plan = review(f); f.capture().complete(plan); const s = f.state.getSnapshot(); f.state.set({ ...s, states: { ...s.states, display: { ...s.states.display, draft: { title: { kind: 'value', value: 'Changed outside observer' } } } } }); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual([]); f.capture().mode('group'); edit(f); f.capture().preview(); f.dispose(); f.dispose(); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual([]); expect(f.state.getSnapshot().available).toBe(false); await app.dispose(); });
});
it('stages supported local override removal without resolving fallback or changing presence/value metadata', async () => { const { app, fixture: f } = controlled(); f.capture().draft('display', { count: { kind: 'unset' } }); expect(f.state.getSnapshot().states.display.draft).toEqual({}); f.capture().draft('display', { title: { kind: 'unset' } }); f.capture().preview(); f.release(); await Promise.resolve(); expect(f.state.getSnapshot().plan).toEqual([{ groupId: 'display', changes: { set: {}, unset: ['title'] } }]); expect(f.state.getSnapshot().states.display.values.title.value).toBe('Authored fixture'); expect(f.state.getSnapshot().states.display.values.title.has_override).toBe(true); expect(f.state.getSnapshot().states.display.apply?.restartRequired).toBe(true); f.dispose(); await app.dispose(); });
