import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {AdminNavigation,AdminContent,AdminShell} from '@hollis-labs/kit-admin';
import type {AdminContentProps} from '@hollis-labs/kit-admin';
import {SampleSeriesView} from '@hollis-labs/kit-observe/charts';
import {Button,DetailDialog,JsonViewer} from '@hollis-labs/design-components';
import {adminAppearances,createAdminReviewFixture} from './admin-review-fixture.js';
import type {createPlaybackFixture} from './playback-fixture.js';
import {PlaybackStartup} from './playback-example.js';
import './admin-review-style.css';
export function AdminReviewProof({app,retainRetired,switchContext,retire,standalone=false}:{app:ReturnType<typeof createPlaybackFixture>;retainRetired:(release:()=>void)=>void;switchContext:()=>void;retire:()=>void;standalone?:boolean}){
 const [fixture,setFixture]=useState<ReturnType<typeof createAdminReviewFixture>|null>(null);
 useEffect(()=>{const next=createAdminReviewFixture(app),releases=[app.frame.subscribe(next.refresh),app.runtime.subscribe(next.refresh)],route=()=>next.route(location.hash);window.addEventListener('hashchange',route);next.refresh();setFixture(next);return()=>{window.removeEventListener('hashchange',route);releases.forEach(release=>release());retainRetired(next.release);next.dispose()}},[app,retainRetired]);
 return fixture?<AdminReviewBody app={app} fixture={fixture} switchContext={switchContext} retire={retire} standalone={standalone}/>:<p>Loading controlled admin lifetime</p>;
}
function AdminReviewBody({app,fixture,switchContext,retire,standalone}:{app:ReturnType<typeof createPlaybackFixture>;fixture:ReturnType<typeof createAdminReviewFixture>;switchContext:()=>void;retire:()=>void;standalone:boolean}){
 const snapshot=useSyncExternalStore(fixture.state.subscribe,fixture.state.getSnapshot,fixture.state.getSnapshot),callbacks=fixture.capture(),section=useRef<HTMLElement>(null),origin=useRef<HTMLElement|null>(null),previous=useRef({identity:snapshot.identity,open:snapshot.open}),pending=useRef<'heading'|'origin'|null>(null);
 const props:AdminContentProps={...fixture.projection(),destination:fixture.destination,renderSeries:snapshot.appearance==='series-present'?props=><SampleSeriesView {...props}/>:undefined};
 useEffect(()=>{if(previous.current.identity!==snapshot.identity)pending.current='heading';else if(previous.current.open&&!snapshot.open)pending.current='origin';if(snapshot.open)pending.current=null;previous.current={identity:snapshot.identity,open:snapshot.open};if(!pending.current||snapshot.open)return;let node=pending.current==='heading'?(standalone?section.current?.querySelector<HTMLElement>('h1'):section.current?.closest('main')?.querySelector<HTMLElement>('h1')):origin.current;if(node instanceof HTMLButtonElement&&node.disabled)node=section.current?.querySelector<HTMLButtonElement>('button');const id=requestAnimationFrame(()=>{const live=fixture.state.getSnapshot();if(fixture.current(snapshot.identity)&&live.controlEpoch===snapshot.controlEpoch&&!live.open&&node?.isConnected){node.focus();pending.current=null}});return()=>cancelAnimationFrame(id)},[fixture,snapshot.identity,snapshot.open,snapshot.controlEpoch,standalone]);
 const controls=<nav aria-label="Admin local review controls"><Button onClick={callbacks.href}>Toggle admin destination mode</Button><Button disabled={!fixture.allowed({page:'settings',groupId:'appearance'})||snapshot.busy} onClick={()=>callbacks.inspect({page:'settings',groupId:'appearance'})}>Hold declared destination inspection</Button><Button disabled={!snapshot.intent||snapshot.open} onClick={event=>{origin.current=event.currentTarget;callbacks.open(true)}}>Inspect local admin destination</Button><Button onClick={fixture.release}>Release admin destination producer</Button></nav>;
 const modal=<DetailDialog open={snapshot.open} onClose={()=>callbacks.open(false)} title="Local admin destination inspection" footer={<Button onClick={()=>callbacks.open(false)}>Close admin destination inspection</Button>}><div className="admin-destination-body"><p>Destination inspection only. No settings, snapshots, manifest or business effects are changed.</p><JsonViewer value={snapshot.intent} className="whitespace-pre-wrap [overflow-wrap:anywhere]"/><nav><Button onClick={()=>{void app.load('/api/overlay-registry')}}>Replace generation from admin inspection</Button><Button onClick={()=>{void app.registry.unload('fake-ops')}}>Withdraw owner from admin inspection</Button><Button onClick={()=>app.retireSource()}>Retire source from admin inspection</Button><Button onClick={switchContext}>Switch context from admin inspection</Button><Button onClick={callbacks.manifest}>Replace manifest from admin inspection</Button><Button onClick={callbacks.group}>Switch group from admin inspection</Button><Button onClick={retire}>Unmount from admin inspection</Button><Button onClick={fixture.release}>Release held admin inspection</Button></nav></div></DetailDialog>;
 if(standalone)return <section ref={section} className="admin-standalone-review" aria-label="Standalone controlled AdminShell"><div className="admin-standalone-controls"><h1 tabIndex={-1}>Standalone read-only admin shell</h1><p>Authored offline data; {snapshot.href?'same-origin fragment':'local callback'} navigation only.</p>{controls}<p role="status" aria-label="Admin destination outcome">{snapshot.output}</p></div><div className="admin-shell-region">{snapshot.available?<AdminShell {...props}/>:<p>Actual contribution withdrawn.</p>}</div>{modal}</section>;
 return <section ref={section} className="admin-review-proof" aria-label="Controlled admin destination review"><h2>Authored offline read-only administration</h2><p>Three pinned admin exports. Main review uses Navigation+Content within the host; standalone entry owns one actual AdminShell. No settingsActions, setup, provider, saving/applying or persistence. Diagnostics observations omitted to avoid unconditional clipboard action. Retained valid declarations allow native navigation.</p><p>Admin lease: {snapshot.identity}</p><p>Destination mode: {snapshot.href?'same-origin fragment':'local onSelect'}; current page: {snapshot.selection.page}; group: {snapshot.selection.groupId??'none'}. All supplied settings and observations remain read-only.</p><nav aria-label="Admin appearances">{adminAppearances.map(value=><Button key={value} aria-pressed={snapshot.appearance===value} onClick={()=>callbacks.appearance(value)}>Admin {value}</Button>)}</nav>{controls}<nav aria-label="Admin lifetime controls"><Button onClick={callbacks.manifest}>Replace authored manifest revision</Button><Button onClick={callbacks.group}>Switch authored settings group</Button></nav>{snapshot.available?<div className="admin-review-columns"><AdminNavigation {...props}/><AdminContent {...props}/></div>:<p>Actual contribution withdrawn; declared destinations retired.</p>}<p role="status" aria-label="Admin destination outcome">{snapshot.output}</p>{modal}</section>;
}
export function AdminReviewStartup({standalone=false}:{standalone?:boolean}){const retired=useRef<()=>void>(()=>{}),retain=useRef((release:()=>void)=>{retired.current=release});return <><PlaybackStartup adminReview adminShellReview={standalone} retainAdminProducer={retain.current}/>{!standalone&&<Button onClick={()=>retired.current()}>Release retired admin destination producer</Button>}</>}
