import {adminManifestProblem,adminPages} from '@hollis-labs/kit-admin';
import type {AdminContentProps,AdminManifest,AdminTarget,AdminSelection} from '@hollis-labs/kit-admin';
import {readOnlyAdminFixture} from '../src/admin-fixture.js';
import {createAdminPresentationSession} from '../src/admin-session.js';
import {store} from '../src/store.js';
import type {createPlaybackFixture} from './playback-fixture.js';
export const adminAppearances=['ready','initial-loading','initial-error','retained-loading','retained-error','context-mismatch','unsupported','malformed','contradictory','duplicate','empty','missing-snapshot','group-loading','group-error','invalid-metadata','unknown-page','unknown-group','series-absent','series-present'] as const;
export type AdminAppearance=typeof adminAppearances[number];
const now=Date.parse('2026-10-08T02:00:05Z'),receipt='2026-10-08T02:00:00Z';
export function createAdminReviewFixture(app:ReturnType<typeof createPlaybackFixture>){
 let disposed=false,lease=0,revision='authored-v1',appearance:AdminAppearance='ready',selection:AdminSelection={page:'dashboard'},href=false;
 const pending:(()=>void)[]=[];
 const readScope=()=>{const frame=app.frame.getSnapshot(),view=app.select('operations.detail').find(v=>v.ref.owner==='fake-ops');const hostKey=`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}`;return {hostKey,identity:`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}/${revision}/${appearance}/${selection.page}/${selection.groupId??'none'}/${href}`,available:!!view&&app.runtime.isCurrent(view)}};
 let scope=readScope();const session=createAdminPresentationSession(app.frame.getSnapshot().contextKey,scope.identity,['destination']);
 const empty=()=>({...scope,controlEpoch:lease,revision,appearance,selection,href,busy:false,open:false,intent:null as null|{kind:'local-destination-inspection';revision:string;from:AdminSelection;target:AdminTarget},output:'No local destination inspection'});
 const state=store(empty());
 function refresh(){if(disposed)return;let next=readScope();if(next.hostKey!==scope.hostKey){selection={page:'dashboard'};next=readScope()}if(next.identity===scope.identity&&next.available===scope.available)return;scope=next;lease++;session.reset(app.frame.getSnapshot().contextKey,`${scope.identity}/${scope.available}/${lease}`);state.set(empty())}
 function retireLocal(){lease++;session.reset(app.frame.getSnapshot().contextKey,`${scope.identity}/${lease}`);state.set(empty())}
 function current(identity:string){refresh();return !disposed&&scope.identity===identity}
 function projection(){const contextKey=app.frame.getSnapshot().contextKey,base=readOnlyAdminFixture(contextKey,now), original=base.discovery.manifest!;
 const group={...original.settings[0],schema:{type:'object',additionalProperties:false,properties:{mode:{type:'string',title:'Mode',readOnly:true},count:{type:'integer',title:'Known zero',readOnly:true},enabled:{type:'boolean',title:'Explicit false',readOnly:true}}},fields:{mode:{editable:false,secret:false,restart_required:false,read_only_reason:'Offline read-only projection'},count:{editable:false,secret:false,restart_required:false,read_only_reason:'Offline read-only projection'},enabled:{editable:false,secret:false,restart_required:false,read_only_reason:'Offline read-only projection'}}};
 let manifest:AdminManifest={...original,app:{id:'offline-admin',label:'Authored offline administration'},revision,settings:[group,{...group,id:'limits',label:'Resource limits'}],health:[{id:'provider',label:'Authored health',section:'status',stale_after_ms:5000}],stats:[{id:'zero',label:'Recorded zero',section:'status',stale_after_ms:5000,unit:'count',kind:'counter'}],series:[{id:'series',label:'Authored exact series',section:'diagnostics',stale_after_ms:5000,unit:'count',kind:'counter',max_points:3,max_window_seconds:4}],diagnostics:[{...original.diagnostics[0],label:'Diagnostic observation omitted',stale_after_ms:5000}]};
 if(appearance==='unsupported')manifest={...manifest,contract_version:2};if(appearance==='malformed')manifest={...manifest,revision:''};if(appearance==='contradictory')manifest={...manifest,health:[{...manifest.health[0],section:'settings'}]};if(appearance==='duplicate')manifest={...manifest,settings:[group,group]};if(appearance==='empty')manifest={...manifest,settings:[],health:[],stats:[],series:[],diagnostics:[]};
 const value=base.settings!.appearance!.state!;const snapshot={...value,values:{...value.values,count:{present:true,value:0,editable:false,has_override:false,read_only_reason:'Offline read-only projection',source:{kind:'default' as const,label:'Authored defaults'},apply_state:'active' as const},enabled:{present:true,value:false,editable:false,has_override:false,read_only_reason:'Offline read-only projection',source:{kind:'env' as const,label:'Authored environment'},apply_state:'active' as const}}};
 const settings:AdminContentProps['settings']=appearance==='missing-snapshot'?{}:{appearance:{phase:appearance==='group-loading'?'loading':appearance==='group-error'?'error':'ready',state:appearance==='invalid-metadata'?{...snapshot,values:{}}:snapshot,error:appearance==='group-error'?'Authored group read error':undefined},limits:{phase:'ready',state:snapshot}};
 const observation={phase:'ready' as const,observedAt:receipt,nowMs:now,staleAfterMs:5000};
 const discovery:AdminContentProps['discovery']={phase:appearance==='initial-loading'||appearance==='retained-loading'?'loading':appearance==='initial-error'||appearance==='retained-error'?'error':'ready',contextKey:appearance==='context-mismatch'?'retired-context':contextKey,manifest:appearance==='initial-loading'||appearance==='initial-error'?undefined:manifest,error:appearance==='initial-error'||appearance==='retained-error'?'Authored discovery failure':undefined};
 return{contextKey,discovery,selection:appearance==='unknown-page'?{page:'unknown' as AdminSelection['page']}:appearance==='unknown-group'?{page:'settings' as const,groupId:'unknown'}:selection,settings,observations:{health:{provider:{status:'degraded' as const,checks:[],observation}},stats:{zero:{value:0,observation}},series:{series:{points:[{at:'2026-10-08T01:59:56Z',value:0},{at:'2026-10-08T01:59:58Z',value:null},{at:receipt,value:1}],requested:{from:'2026-10-08T01:59:56Z',to:receipt,limit:3},truncated:false,observation}}},nowMs:now};
 }
 function allowed(target:AdminTarget){const props=projection(),manifest=props.discovery.manifest;if(!scope.available||props.discovery.contextKey!==props.contextKey||!manifest||adminManifestProblem(manifest))return false;return adminPages(manifest).includes(target.page)&&(target.groupId===undefined||(target.page==='settings'&&manifest.settings.some(group=>group.id===target.groupId)))}
 const canonical=(target:AdminTarget)=>`#admin-review/${target.page}${target.groupId?`/${target.groupId}`:''}?scope=${encodeURIComponent(scope.identity)}&lease=${lease}`;
 function capture(){refresh();const identity=scope.identity,stamp=lease,valid=()=>{refresh();return !disposed&&scope.available&&identity===scope.identity&&stamp===lease};return {
  navigate(target:AdminTarget){if(valid()&&allowed(target)){if(appearance==='unknown-page'||appearance==='unknown-group')appearance='ready';selection={...target};refresh()}},
  inspect(target:AdminTarget){if(!valid()||!allowed(target)||state.getSnapshot().busy)return;const intent={kind:'local-destination-inspection' as const,revision,from:{...projection().selection},target:{...target}},ticket=session.begin('destination'),held=++lease;state.set({...state.getSnapshot(),controlEpoch:lease,busy:true,intent,output:'Held local destination candidate; no business effects'});void new Promise<void>(resolve=>pending.push(resolve)).then(()=>{refresh();if(disposed||scope.identity!==identity||lease!==held||!allowed(intent.target)||revision!==intent.revision){ticket.cancel();return}ticket.commit(()=>state.set({...state.getSnapshot(),busy:false,output:'Inspected local destination only; supplied records unchanged'}))});},
  appearance(value:AdminAppearance){if(valid()&&adminAppearances.includes(value)){appearance=value;selection=value.includes('snapshot')||value.startsWith('group-')||value==='invalid-metadata'?{page:'settings',groupId:'appearance'}:value.startsWith('series-')?{page:'diagnostics'}:{page:'dashboard'};refresh()}},
  manifest(){if(valid()){revision=revision==='authored-v1'?'authored-v2':'authored-v1';selection={page:'dashboard'};refresh()}},
  group(){if(valid()){selection={page:'settings',groupId:selection.groupId==='limits'?'appearance':'limits'};refresh()}},
  href(){if(valid()){href=!href;refresh()}},
  open(open:boolean){if(!valid()||!state.getSnapshot().intent)return;if(open)state.set({...state.getSnapshot(),open:true});else retireLocal()}
 }}
 function destination(target:AdminTarget){const callbacks=capture();return href&&allowed(target)?{href:canonical(target)}:{onSelect:()=>callbacks.navigate(target)}}
 function route(hash:string){refresh();if(disposed)return;const target=projection().discovery.manifest;if(!target||adminManifestProblem(target))return;const known:AdminTarget[]=[...adminPages(target).map(page=>({page})),...target.settings.map(group=>({page:'settings' as const,groupId:group.id}))];const match=known.find(target=>canonical(target)===hash);if(match)capture().navigate(match)}
 return{state,refresh,current,capture,projection,destination,route,allowed,release(){pending.splice(0).forEach(resolve=>resolve())},dispose(){if(disposed)return;disposed=true;lease++;session.dispose();state.set({...empty(),available:false})}};
}
