import {createAdminPresentationSession} from '../src/admin-session.js';
import {store} from '../src/store.js';
import type {createPlaybackFixture} from './playback-fixture.js';
export const developerFiles=Object.freeze({'src/verify.ts':'// Authored offline source; never executed\nexport const expected = 0;\nexport const actual = null;\n// retained fictional failure location','src/empty.ts':'','src/inert.ts':'<script>globalThis.executed = true</script>\n'+('long inert source '.repeat(18))});
export const developerTests=Object.freeze([{id:'zero',name:'Known zero-duration assertion',status:'passed' as const,duration:0,file:'src/verify.ts',line:2},{id:'failure',name:'Authored failed assertion with long diagnostic',status:'failed' as const,duration:1250,file:'src/verify.ts',line:3},{id:'skip',name:'Authored skipped test',status:'skipped' as const,duration:undefined,file:'src/empty.ts',line:undefined},{id:'running',name:'Passive supplied running appearance',status:'running' as const,duration:undefined,file:'src/inert.ts',line:1}]);
export const developerTrace='AssertionError: fictional expected zero, received no sample\n    at verify (src/verify.ts:3:1)\n    at hidden (node:internal/fixtures:1:1)\n    raw unknown frame remains literal text';
export type DeveloperEvidencePhase='ready'|'missing'|'empty'|'loading'|'error'|'denied'|'unknown'|'locked';
export function createDeveloperEvidenceFixture(app:ReturnType<typeof createPlaybackFixture>){let disposed=false,lease=0,phase:DeveloperEvidencePhase='ready';const pending:(()=>void)[]=[];
 const scope=()=>{const frame=app.frame.getSnapshot(),view=app.select('operations.detail').find(v=>v.ref.owner==='fake-ops');return{identity:`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${frame.cutoff}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}/${phase}`,available:!!view&&app.runtime.isCurrent(view)}};
 let current=scope();const session=createAdminPresentationSession(app.frame.getSnapshot().contextKey,current.identity,['inspection']);
 const fresh=()=>({...current,phase,controlEpoch:lease,selected:'failure',path:'src/verify.ts',line:3 as number|undefined,expanded:new Set(['src']),suiteOpen:true,stackOpen:true,commitOpen:true,internal:false,busy:false,output:'No local developer inspection'});
 const state=store(fresh());
 function refresh(){if(disposed)return;const next=scope();if(next.identity===current.identity&&next.available===current.available)return;current=next;lease++;session.reset(app.frame.getSnapshot().contextKey,`${current.identity}/${current.available}/${lease}`);state.set(fresh())}
 function change(update:Partial<ReturnType<typeof fresh>>){lease++;session.reset(app.frame.getSnapshot().contextKey,`${current.identity}/${lease}`);state.set({...state.getSnapshot(),...update,controlEpoch:lease,busy:false,output:'No local developer inspection'})}
 function capture(){refresh();const identity=current.identity,epoch=lease,valid=()=>{refresh();return !disposed&&current.available&&current.identity===identity&&lease===epoch},editable=()=>valid()&&phase==='ready';return{
  phase(value:DeveloperEvidencePhase){if(valid()&&['ready','missing','empty','loading','error','denied','unknown','locked'].includes(value)){phase=value;refresh()}},
  select(id:string){if(!editable())return;const test=developerTests.find(test=>test.id===id);if(test)change({selected:id,path:test.file,line:test.line})},
  file(path:string,line?:number,column?:number){if(!editable())return;if(!Object.hasOwn(developerFiles,path)){change({});state.set({...state.getSnapshot(),output:'Source unavailable: path outside the authored file catalog'});return;}const text=developerFiles[path as keyof typeof developerFiles],lines=text?text.split('\n'):[];if(line!==undefined&&(!Number.isSafeInteger(line)||line<1||line>lines.length)){change({});state.set({...state.getSnapshot(),output:'Source location unavailable: line outside the authored file'});return;}if(column!==undefined&&(!Number.isSafeInteger(column)||column<1||line===undefined||column>lines[line-1].length+1)){change({});state.set({...state.getSnapshot(),output:'Source location unavailable: column outside the authored file'});return;}change({path,line})},
  expand(expanded:Set<string>){if(editable()&&Array.from(expanded).every(path=>path==='src'))change({expanded:new Set(expanded)})},
  suite(value:boolean){if(editable())change({suiteOpen:value})},stack(value:boolean){if(editable())change({stackOpen:value})},commit(value:boolean){if(editable())change({commitOpen:value})},internal(){if(editable())change({internal:!state.getSnapshot().internal})},
  hold(){if(!editable()||state.getSnapshot().busy)return;const selected=state.getSnapshot(),target={test:selected.selected,path:selected.path,line:selected.line},ticket=session.begin('inspection'),stamp=++lease;state.set({...selected,controlEpoch:lease,busy:true,output:'Held local developer candidate; no tests/code/commit operation executes'});void new Promise<void>(resolve=>pending.push(resolve)).then(()=>{refresh();const live=state.getSnapshot();if(disposed||!current.available||current.identity!==identity||lease!==stamp||phase!=='ready'||live.selected!==target.test||live.path!==target.path||live.line!==target.line){ticket.cancel();return}ticket.commit(()=>state.set({...live,busy:false,output:`Inspected supplied ${target.test}/${target.path}${target.line===undefined?'':`:${target.line}`} locally; evidence unchanged`}))})}
 }}
 return{state,refresh,capture,current(identity:string,epoch?:number){refresh();return !disposed&&current.identity===identity&&(epoch===undefined||lease===epoch)},release(){pending.splice(0).forEach(resolve=>resolve())},dispose(){if(disposed)return;disposed=true;lease++;session.dispose();state.set({...fresh(),available:false,busy:false,output:'No local developer inspection'})}};
}
