import {useEffect,useId,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {AppShell,Button,Tooltip,TooltipTrigger,TooltipContent,TooltipProvider,Skeleton,Separator} from '@hollis-labs/design-components';
import {WidgetRenderer,PluginPanelBody} from '@hollis-labs/plugin-host-ui/react';
import {createEvidenceStates,type EvidencePhase} from './evidence-states-fixture.js';
import type {createPlaybackFixture} from './playback-fixture.js';
import {PlaybackStartup} from './playback-example.js';
import './evidence-states-style.css';
type App=ReturnType<typeof createPlaybackFixture>;
export function EvidenceStatesProof({app,switchContext,retire}:{app:App;switchContext:()=>void;retire:()=>void}){const[fixture,setFixture]=useState<ReturnType<typeof createEvidenceStates>|null>(null);useEffect(()=>{const next=createEvidenceStates(app),releases=[app.frame.subscribe(next.refresh),app.runtime.subscribe(next.refresh)];setFixture(next);return()=>{releases.forEach(r=>r());next.dispose()}},[app]);return fixture?<EvidenceStates app={app} fixture={fixture} switchContext={switchContext} retire={retire}/>:<p>Loading evidence-state lifetime</p>}
function EvidenceStates({app,fixture,switchContext,retire}:{app:App;fixture:ReturnType<typeof createEvidenceStates>;switchContext:()=>void;retire:()=>void}){const snapshot=useSyncExternalStore(fixture.state.subscribe,fixture.state.getSnapshot,fixture.state.getSnapshot),frame=useSyncExternalStore(app.frame.subscribe,app.frame.getSnapshot,app.frame.getSnapshot),callbacks=useMemo(()=>fixture.capture(),[fixture,snapshot.identity,snapshot.epoch]),headerRef=useRef<HTMLElement>(null),previous=useRef(snapshot.identity);useEffect(()=>{if(previous.current===snapshot.identity)return;previous.current=snapshot.identity;const node=headerRef.current,origin=document.activeElement;if(origin?.closest('[data-evidence-independent]'))return;const id=requestAnimationFrame(()=>{if(fixture.current(snapshot.identity,snapshot.epoch)&&node?.isConnected&&(document.activeElement===origin||document.activeElement===document.body))node.focus()});return()=>cancelAnimationFrame(id)},[fixture,snapshot.identity,snapshot.epoch]);const ready=fixture.present(),count=fixture.count(),view=app.select('operations.detail').find(v=>v.ref.owner==='fake-ops'),facts=`Authored offline evidence-state sample. Count ${count===null?'Unknown':count}; review cutoff ${snapshot.utc}. No provider fetch or production observation.`,help=snapshot.phase==='long'?`${facts} ${'Supplemental literal source text. '.repeat(5)}<script>globalThis.evidenceHelpExecuted=true</script>`:facts;
 const helpId=`${useId()}-${encodeURIComponent(snapshot.identity)}-${snapshot.delayed?'delayed':'default'}`;
 const header=<header ref={headerRef} tabIndex={-1} aria-label="Evidence state header" className="evidence-header"><h1>Authored evidence states and source help</h1><p>Readonly authored specimens under actual current Detail, not business records or provider evidence. Tooltip repeats ordinary visible facts.</p><details><summary>Evidence lifecycle controls</summary><nav aria-label="Evidence lifecycle"><Button onClick={()=>{void app.load('/api/overlay-registry')}}>Replace evidence generation</Button><Button onClick={()=>{void app.registry.unload('fake-ops')}}>Withdraw evidence owner</Button><Button onClick={()=>app.retireSource()}>Retire evidence source</Button><Button onClick={()=>app.seek(frame.index===3?0:frame.index+1)}>Advance evidence cutoff</Button><Button onClick={switchContext}>Switch evidence context</Button><Button onClick={retire}>Unmount evidence consumer</Button></nav></details><nav aria-label="Evidence states">{(['ready','empty','loading','error','denied','unknown','long'] as EvidencePhase[]).map(phase=><Button key={phase} aria-label={`Evidence ${phase}`} aria-pressed={snapshot.phase===phase} onClick={()=>callbacks.phase(phase)}>{phase}</Button>)}{app.select('operations.summary').filter(v=>v.ref.key==='stable').map(v=><span data-evidence-independent key={`${v.id}/${frame.epoch}`}><WidgetRenderer widget={v}/></span>)}</nav></header>;
 return <AppShell header={header}><main className="evidence-main" aria-label="Evidence state review"><section aria-label="Current authored evidence state"><h2>Current state: {snapshot.available?snapshot.phase:'withdrawn'}</h2><p aria-label="Authored evidence count">Count: {count===null?'Unknown':count} authored items</p><p>{facts}</p>{snapshot.phase==='loading'&&snapshot.available?<div role="status" aria-label="Authored loading presentation" aria-busy="true"><p>Loading is an authored appearance, not measured progress or a fetch.</p><div aria-hidden="true" className="evidence-skeletons"><Skeleton className="h-6 w-3/4 motion-reduce:animate-none"/><Skeleton className="h-6 w-full motion-reduce:animate-none"/><Skeleton className="h-6 w-1/2 motion-reduce:animate-none"/></div></div>:!ready?<p role={snapshot.phase==='error'?'alert':'status'}>Content and known counts withheld; unavailable is not successful empty zero.</p>:<><p>Successful supplied {snapshot.phase==='empty'?'empty':'finite'} authored specimen; only the manual cutoff supplies its bounded count.</p><p aria-label="Visible source help facts">{help}</p><TooltipProvider delay={snapshot.delayed?200:0}><Tooltip key={`${snapshot.identity}/${snapshot.delayed}`} open={snapshot.open} onOpenChange={callbacks.open}><TooltipTrigger aria-describedby={snapshot.open?helpId:undefined} className="evidence-help-trigger">Supplemental source help</TooltipTrigger><TooltipContent role="tooltip" id={helpId} className="evidence-help-content motion-reduce:animate-none">{help}</TooltipContent></Tooltip></TooltipProvider><Button onClick={callbacks.delay} aria-pressed={snapshot.delayed}>Help delay: {snapshot.delayed?'200ms':'default 0ms'}</Button></>}</section><Separator aria-label="Authored state and provenance separation"/><section className="evidence-raw" aria-label="Current evidence provenance"><h2>Exact current provenance</h2><dl><dt>Appearance / authored count</dt><dd>{snapshot.phase}; {count===null?'null / Unknown':count}</dd><dt>Review cutoff</dt><dd>{snapshot.utc}</dd><dt>Current contribution</dt><dd>{view?.ref.hostInstance??'Unavailable'}; {view?.id??'Unavailable'}; {view?.ref.owner??'Unavailable'}/{view?.ref.key??'Unavailable'}; generation {view?.ref.generation??'Unavailable'}; {frame.contextLabel}</dd><dt>Tooltip policy</dt><dd>Nonessential repeated facts; default position only; supplied delay {snapshot.delayed?200:0}ms. Implicit Arrow unclaimed.</dd></dl><p>No persisted state, business operation or provider effect.</p></section>{ready&&view&&app.runtime.isCurrent(view)&&<section aria-label="Actual Detail contribution"><PluginPanelBody panel={view}/></section>}</main></AppShell>}
export function EvidenceStatesStartup(){return <PlaybackStartup evidenceStates/>}
