import {createAdminPresentationSession} from '../src/admin-session.js';
import {store} from '../src/store.js';
import {playbackBoundaries,type createPlaybackFixture} from './playback-fixture.js';
export type ExplorerPhase='ready'|'absent'|'loading'|'error'|'denied'|'empty';
export type ExplorerEvidence='any'|'reported'|'zero'|'unknown';
export type ExplorerRow={id:string;title:string;owner:string;queuedAt:string;status:'queued'|'running'|'completed';receipt:null|{observedAt:string;units:number|null};units:number|null};
const authored=Object.freeze(Array.from({length:32},(_,index)=>Object.freeze({id:`local-run-${String(index+1).padStart(2,'0')}`,title:`Authored run ${String(index+1).padStart(2,'0')}`,owner:index%2?'fixture-beta':'fixture-alpha',queuedAt:playbackBoundaries[Math.floor(index/8)],startedAt:playbackBoundaries[Math.min(3,Math.floor(index/8)+1)],finishedAt:index<16?playbackBoundaries[Math.floor(index/8)+2]:null})));
const receipts=Object.freeze(authored.filter(row=>row.finishedAt!==null).map((row,index)=>Object.freeze({runId:row.id,at:row.finishedAt!,units:index%3===0?0:index%3===1?null:(index+1)*12})));
export function createExplorerReviewFixture(app:ReturnType<typeof createPlaybackFixture>){
 let disposed=false,lease=0,phase:ExplorerPhase='ready',query='',statuses:string[]=[],owner:string|null=null,evidence:ExplorerEvidence='any';const pending:(()=>void)[]=[];
 const readScope=()=>{const frame=app.frame.getSnapshot(),view=app.select('operations.detail').find(v=>v.ref.owner==='fake-ops');return{identity:`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${frame.cutoff}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}/${phase}/${query}/${statuses.join(',')}/${owner}/${evidence}`,hostKey:`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}`,available:!!view&&app.runtime.isCurrent(view)}};
 let scope=readScope();const session=createAdminPresentationSession(app.frame.getSnapshot().contextKey,scope.identity,['inspection']);
 function projected():ExplorerRow[]{if(phase!=='ready')return[];const cutoff=app.frame.getSnapshot().cutoff;return authored.filter(row=>row.queuedAt<=cutoff).map(row=>{const receipt=receipts.find(receipt=>receipt.runId===row.id&&receipt.at<=cutoff);return{id:row.id,title:row.title,owner:row.owner,queuedAt:new Date(row.queuedAt).toISOString(),status:row.finishedAt!==null&&row.finishedAt<=cutoff?'completed':row.startedAt<=cutoff?'running':'queued',receipt:receipt?{observedAt:new Date(receipt.at).toISOString(),units:receipt.units}:null,units:receipt?.units??null}})}
 function empty(){const admitted=scope.available?projected():[],rows=admitted.filter(row=>(!query.trim()||`${row.id} ${row.title} ${row.owner} ${row.status}`.toLowerCase().includes(query.trim().toLowerCase()))&&(!statuses.length||statuses.includes(row.status))&&(!owner||row.owner===owner)&&(evidence==='any'||evidence==='reported'&&row.receipt!==null||evidence==='zero'&&row.receipt!==null&&row.units===0||evidence==='unknown'&&row.units===null));return{...scope,controlEpoch:lease,phase,query,statuses:[...statuses],owner,evidence,admitted,rows,density:'compact' as 'compact'|'comfortable',selected:[] as string[],visible:[] as string[],record:null as ExplorerRow|null,busy:false,result:'No local record inspection'}}
 const state=store(empty());
 function refresh(){if(disposed)return;let next=readScope();if(next.hostKey!==scope.hostKey){query='';statuses=[];owner=null;evidence='any';next=readScope()}if(next.identity===scope.identity&&next.available===scope.available)return;scope=next;lease++;session.reset(app.frame.getSnapshot().contextKey,`${scope.identity}/${scope.available}/${lease}`);state.set(empty())}
 function current(identity:string){refresh();return !disposed&&scope.identity===identity}
 function capture(){refresh();const identity=scope.identity,stamp=lease,valid=()=>{refresh();return !disposed&&scope.available&&scope.identity===identity&&lease===stamp},eligible=()=>valid()&&phase==='ready';return{
  query(value:string){if(valid()){query=value;refresh()}},status(value:string){if(eligible()&&['queued','running','completed'].includes(value)){statuses=statuses.includes(value)?statuses.filter(status=>status!==value):[...statuses,value].sort();refresh()}},owner(value:string|null){if(eligible()&&(value===null||state.getSnapshot().admitted.some(row=>row.owner===value))){owner=value;refresh()}},evidence(value:ExplorerEvidence){if(eligible()&&['any','reported','zero','unknown'].includes(value)){evidence=value;refresh()}},clear(){if(valid()){query='';statuses=[];owner=null;evidence='any';refresh()}},phase(value:ExplorerPhase){if(valid()&&['ready','absent','loading','error','denied','empty'].includes(value)){phase=value;query='';statuses=[];owner=null;evidence='any';refresh()}},density(){if(valid())state.set({...state.getSnapshot(),density:state.getSnapshot().density==='compact'?'comfortable':'compact'})},
  visible(ids:string[]){if(!eligible()||ids.some(id=>!state.getSnapshot().rows.some(row=>row.id===id)))return;if(JSON.stringify(ids)!==JSON.stringify(state.getSnapshot().visible))state.set({...state.getSnapshot(),visible:[...ids]})},
  selected(ids:string[]){if(!eligible()||new Set(ids).size!==ids.length||ids.some(id=>!state.getSnapshot().rows.some(row=>row.id===id)))return;if(JSON.stringify(ids)!==JSON.stringify(state.getSnapshot().selected))state.set({...state.getSnapshot(),selected:[...ids]})},
  open(id:string,row:ExplorerRow){if(!eligible()||!state.getSnapshot().rows.some(current=>current.id===id&&current===row))return;lease++;session.reset(app.frame.getSnapshot().contextKey,`${scope.identity}/${lease}`);state.set({...state.getSnapshot(),controlEpoch:lease,record:row,busy:false,result:'No local record inspection'})},
  close(){if(valid()){lease++;session.reset(app.frame.getSnapshot().contextKey,`${scope.identity}/${lease}`);state.set({...state.getSnapshot(),controlEpoch:lease,record:null,busy:false,result:'No local record inspection'})}},
  hold(){if(!eligible()||!state.getSnapshot().record||state.getSnapshot().busy)return;const record=state.getSnapshot().record!,ticket=session.begin('inspection'),held=++lease;state.set({...state.getSnapshot(),controlEpoch:lease,busy:true,result:'Held local readonly record candidate'});void new Promise<void>(resolve=>pending.push(resolve)).then(()=>{refresh();if(disposed||scope.identity!==identity||lease!==held||!scope.available||phase!=='ready'||state.getSnapshot().record!==record||!state.getSnapshot().rows.includes(record)){ticket.cancel();return}ticket.commit(()=>state.set({...state.getSnapshot(),busy:false,result:`Inspected ${record.id} locally; supplied evidence unchanged`}))});}
 }}
 return{state,refresh,current,capture,release(){pending.splice(0).forEach(resolve=>resolve())},dispose(){if(disposed)return;disposed=true;lease++;session.dispose();state.set({...empty(),available:false,record:null,busy:false,result:'No local record inspection'})}};
}
