import {useEffect,useLayoutEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {AppShell,Button,DetailSection,JsonViewer,type ColumnDef} from '@hollis-labs/design-components';
import {FilterChipGroup,FilterCycleToggle,FilterEntityCombobox} from '@hollis-labs/kit-dashboard/data';
import {OperationsTablePage} from '@hollis-labs/kit-dashboard/layout';
import {PluginPanelBody,WidgetRenderer} from '@hollis-labs/plugin-host-ui/react';
import {createExplorerReviewFixture,type ExplorerRow,type ExplorerPhase} from './explorer-review-fixture.js';
import type {createPlaybackFixture} from './playback-fixture.js';
import {PlaybackStartup} from './playback-example.js';
import './explorer-review-style.css';
const rowId=(row:ExplorerRow)=>row.id,rowLabel=(row:ExplorerRow)=>`Inspect ${row.id}`;
const columns:ColumnDef<ExplorerRow>[]=[{key:'title',header:'Run',cell:row=>row.title,sortValue:row=>row.title,width:'fill'},{key:'status',header:'Status',cell:row=>row.status,sortValue:row=>row.status},{key:'owner',header:'Owner',cell:row=>row.owner,sortValue:row=>row.owner},{key:'units',header:'Recorded units',cell:row=>row.units===null?row.receipt?'Unknown sample':'No receipt':String(row.units),sortValue:row=>row.units??-1,align:'right'}];
export function ExplorerReviewProof({app,retainRetired,releaseRetired,switchContext,retire}:{app:ReturnType<typeof createPlaybackFixture>;retainRetired:(release:()=>void)=>void;releaseRetired:()=>void;switchContext:()=>void;retire:()=>void}){
 const [fixture,setFixture]=useState<ReturnType<typeof createExplorerReviewFixture>|null>(null);
 useEffect(()=>{const next=createExplorerReviewFixture(app),releases=[app.frame.subscribe(next.refresh),app.runtime.subscribe(next.refresh)];next.refresh();setFixture(next);return()=>{releases.forEach(release=>release());retainRetired(next.release);next.dispose()}},[app,retainRetired]);
 return fixture?<ExplorerReviewBody app={app} fixture={fixture} releaseRetired={releaseRetired} switchContext={switchContext} retire={retire}/>:<p>Loading controlled explorer lifetime</p>;
}
function ExplorerReviewBody({app,fixture,releaseRetired,switchContext,retire}:{app:ReturnType<typeof createPlaybackFixture>;fixture:ReturnType<typeof createExplorerReviewFixture>;releaseRetired:()=>void;switchContext:()=>void;retire:()=>void}){
 const snapshot=useSyncExternalStore(fixture.state.subscribe,fixture.state.getSnapshot,fixture.state.getSnapshot),frame=useSyncExternalStore(app.frame.subscribe,app.frame.getSnapshot,app.frame.getSnapshot),callbacks=useMemo(()=>fixture.capture(),[fixture,snapshot.identity,snapshot.controlEpoch]),heading=useRef<HTMLHeadingElement>(null),inspectHeading=useRef<HTMLHeadingElement>(null),previous=useRef({hostKey:snapshot.hostKey,available:snapshot.available,record:snapshot.record}),region=useRef<HTMLDivElement>(null),pendingFocus=useRef<{label:string|null;text:string;start:number|null;end:number|null}|null>(null);
 const preserve=(update:()=>void,label?:string)=>{const active=document.activeElement,before=fixture.state.getSnapshot(),aria=active?.getAttribute('aria-label'),associated=active instanceof HTMLElement&&(label==='Authored owner filter'?!!active.closest('[role="dialog"]')||aria===label:label?aria===label||label==='Search authored runs'&&aria==='Clear all filters and search'||label==='Receipt evidence'&&aria?.startsWith('Receipt evidence, current:'):region.current?.contains(active));if(associated&&active instanceof HTMLElement)pendingFocus.current={label:label??aria??null,text:active.textContent??'',start:active instanceof HTMLInputElement?active.selectionStart:null,end:active instanceof HTMLInputElement?active.selectionEnd:null};update();const after=fixture.state.getSnapshot();if(after.identity===before.identity||after.hostKey!==before.hostKey||after.available!==before.available)pendingFocus.current=null};
 useLayoutEffect(()=>{const captured=pendingFocus.current;pendingFocus.current=null;if(!captured)return;const target=Array.from(region.current!.querySelectorAll<HTMLElement>('input,button')).find(node=>captured.label?(node.getAttribute('aria-label')===captured.label||captured.label==='Receipt evidence'&&node.getAttribute('aria-label')?.startsWith('Receipt evidence, current:')):node.textContent===captured.text);if(target){target.focus();if(target instanceof HTMLInputElement&&captured.start!==null)target.setSelectionRange(captured.start,captured.end);if(captured.label==='Authored owner filter'){const id=requestAnimationFrame(()=>{const live=fixture.state.getSnapshot();if(fixture.current(snapshot.identity)&&live.controlEpoch===snapshot.controlEpoch&&target.isConnected&&target.getAttribute('aria-expanded')!=='true'&&(document.activeElement===document.body||document.activeElement===target))target.focus()});return()=>cancelAnimationFrame(id)}}},[fixture,snapshot.identity,snapshot.controlEpoch]);
 useEffect(()=>{const active=document.activeElement,relevant=active instanceof HTMLElement&&region.current?.contains(active),retired=snapshot.hostKey!==previous.current.hostKey||snapshot.available!==previous.current.available,focus=retired?(relevant||previous.current.record&&active===document.body?'root':null):snapshot.record!==previous.current.record?(snapshot.record?'inspector':active instanceof HTMLElement&&active.closest('.explorer-table-region')?null:'root'):null;previous.current={hostKey:snapshot.hostKey,available:snapshot.available,record:snapshot.record};if(!focus)return;const node=focus==='root'?heading.current:inspectHeading.current,id=requestAnimationFrame(()=>{const live=fixture.state.getSnapshot();if(fixture.current(snapshot.identity)&&live.controlEpoch===snapshot.controlEpoch&&live.record===snapshot.record&&node?.isConnected)node.focus()});return()=>cancelAnimationFrame(id)},[fixture,snapshot.identity,snapshot.controlEpoch,snapshot.record,snapshot.hostKey,snapshot.available]);
 const unavailable=!snapshot.available||snapshot.phase==='denied',active=snapshot.statuses.length+(snapshot.owner?1:0)+(snapshot.evidence!=='any'?1:0),owners=[...new Set(snapshot.admitted.map(row=>row.owner))].map(owner=>({id:owner,name:owner,count:snapshot.admitted.filter(row=>row.owner===owner).length})),view=app.select('operations.detail').find(view=>view.ref.owner==='fake-ops');
 const facets=<><FilterChipGroup label="Status" chips={['queued','running','completed'].map(value=>({value,label:value}))} selected={snapshot.statuses} onToggle={value=>preserve(()=>callbacks.status(value))}/><FilterCycleToggle ariaLabel="Receipt evidence" options={[{value:'any',label:'Any evidence'},{value:'reported',label:'Receipt present'},{value:'zero',label:'Recorded zero'},{value:'unknown',label:'Unknown units'}]} value={snapshot.evidence} onChange={value=>preserve(()=>callbacks.evidence(value),'Receipt evidence')}/><FilterEntityCombobox icon={<span aria-hidden="true">◎</span>} items={owners} value={snapshot.owner} onChange={value=>preserve(()=>callbacks.owner(value),'Authored owner filter')} allLabel="All authored owners" ariaLabel="Authored owner filter"/></>;
 const header=<header className="explorer-review-header"><h1 ref={heading} tabIndex={-1}>Controlled Run Explorer</h1><p>32 immutable authored offline runs and separate receipts over four existing UTC boundaries. Only admitted prefix/receipt joins are shown; no providers, create/send, persistence or fetch pagination. Cutoff {new Date(frame.cutoff).toISOString()}.</p><details><summary>Explorer lifecycle proof controls</summary><nav aria-label="Explorer lifecycle"><Button onClick={()=>app.seek((frame.index+1)%4)}>Advance explorer cutoff</Button><Button onClick={()=>app.reset()}>Reset explorer cutoff</Button><Button onClick={()=>app.retireSource()}>Retire explorer source</Button><Button onClick={switchContext}>Switch explorer context</Button><Button onClick={()=>{void app.load('/api/overlay-registry')}}>Replace explorer generation</Button><Button onClick={()=>{void app.registry.unload('fake-ops')}}>Withdraw explorer owner</Button><Button onClick={retire}>Unmount explorer consumer</Button><Button onClick={fixture.release}>Release explorer producer</Button><Button onClick={releaseRetired}>Release retired explorer producer</Button></nav></details><nav aria-label="Explorer appearances">{(['ready','absent','loading','error','denied','empty'] as ExplorerPhase[]).map(phase=><Button key={phase} aria-pressed={snapshot.phase===phase} onClick={()=>callbacks.phase(phase)}>Explorer {phase}</Button>)}{app.select('operations.summary').filter(view=>view.ref.key==='stable').map(view=><WidgetRenderer key={`${view.id}/${frame.epoch}`} widget={view}/>)}</nav></header>;
 const error=unavailable?<p role="alert">Explorer access denied or contribution withdrawn; no current records.</p>:snapshot.phase==='absent'?<p>No authored run snapshot supplied.</p>:snapshot.phase==='error'?<p role="alert">Authored run snapshot error; no successful data implied.</p>:undefined;
 return <AppShell header={header}><div ref={region} className={`explorer-review-body ${snapshot.record?'has-inspector':''}`}><section className="explorer-table-region" aria-label="Authored operations table"><OperationsTablePage key={snapshot.identity} title="Authored run directory" searchQuery={snapshot.query} onSearchChange={value=>preserve(()=>callbacks.query(value),'Search authored runs')} searchAriaLabel="Search authored runs" searchPlaceholder="Search current prefix…" activeFilterCount={active} filterSummary={snapshot.phase==='ready'&&!unavailable?`${snapshot.rows.length} matched · ${snapshot.admitted.length} admitted`:'Counts unavailable without a successful current snapshot'} searchMatchCount={snapshot.phase==='ready'&&!unavailable?snapshot.rows.length:undefined} onClear={()=>preserve(callbacks.clear,'Search authored runs')} filterControls={snapshot.phase==='ready'&&!unavailable?facets:<p>Facets withheld without a current ready snapshot.</p>} filterActions={<Button disabled={unavailable} onClick={callbacks.density}>Density {snapshot.density}</Button>} footer={<div className="explorer-review-footer"><p role="status" aria-label="Explorer counts">{(snapshot.phase==='ready'||snapshot.phase==='empty')&&!unavailable?`${snapshot.visible.length} revealed / ${snapshot.rows.length} matched / ${snapshot.admitted.length} admitted · ${snapshot.selected.length} locally selected; finite limit32.`:'Run counts unavailable; no successful current snapshot.'}</p><Button disabled={!snapshot.selected.length} onClick={()=>{const row=snapshot.rows.find(row=>row.id===snapshot.selected[0]);if(row)callbacks.open(row.id,row)}}>Inspect first selected run</Button></div>} items={snapshot.rows} columns={columns} getRowId={rowId} rowAriaLabel={rowLabel} density={snapshot.density} initialSort={{key:'title',dir:'asc'}} selectable pageSize={12} onVisibleOrderChange={callbacks.visible} onSelectionChange={callbacks.selected} onRowOpen={callbacks.open} loading={snapshot.phase==='loading'&&!unavailable} errorState={error} emptyState={<p>{snapshot.phase==='empty'?'Authored snapshot contains no runs.':'No current runs match these filters.'}</p>}/></section>{snapshot.record&&<aside className="explorer-record-inspector" aria-label="Readonly selected run"><h2 ref={inspectHeading} tabIndex={-1}>Readonly {snapshot.record.id}</h2><DetailSection title="Current projected evidence"><JsonViewer value={snapshot.record} className="whitespace-pre-wrap [overflow-wrap:anywhere]"/></DetailSection><Button disabled={snapshot.busy} onClick={callbacks.hold}>Hold local record inspection</Button><Button onClick={callbacks.close}>Close readonly run</Button><p role="status" aria-label="Explorer inspection outcome">{snapshot.result}</p>{view&&app.runtime.isCurrent(view)&&<PluginPanelBody panel={view}/>}</aside>}</div></AppShell>;
}
export function ExplorerReviewStartup(){const retired=useRef<()=>void>(()=>{}),retain=useRef((release:()=>void)=>{retired.current=release}),release=useRef(()=>retired.current());return <PlaybackStartup explorerReview retainExplorerProducer={retain.current} releaseExplorerProducer={release.current}/>}
