import {memo,useEffect,useState,useSyncExternalStore} from 'react'
import {PluginHostProvider,WidgetRenderer} from '@hollis-labs/plugin-host-ui/react'
import {DetailDialog} from '@hollis-labs/design-components'
import type {AppIsolationSnapshot,HostScope,SlotCatalogDefinitions,PluginActionIntent} from '@hollis-labs/plugin-host-ui'
import type {PluginRegistryResponse,KindDescriptor,RegionDescriptor} from '@hollis-labs/plugin-registry'
import inventory from 'virtual:chimera/frame-fixture'
import {createIsolatedComposition,httpFrameDelivery} from '../src/frames.js'
import {createFixtureActions} from '../src/fixture-actions.js'
import {memoryLayoutStorage} from '../src/composition.js'
import {store} from '../src/store.js'
const intents:Record<string,PluginActionIntent>={run:{type:'command',command:'frame-tools/run',arguments:{}},navigate:{type:'navigate',route:'detail',parameters:{}},open:{type:'modal',region:'frames.modal',entry:{owner_id:'frame-tools',local_key:'modal'},props:{}}}
const kinds:Record<string,KindDescriptor>={widget:{schema_version:1,metadata_schema:{},representations:['component'],regions:['frames.body','frames.modal'],required_capabilities:[]},command:{schema_version:1,metadata_schema:{},representations:['handler'],regions:['frames.commands'],required_capabilities:[]}}
const regions:Record<string,RegionDescriptor>=Object.fromEntries(['frames.body','frames.modal','frames.commands'].map(name=>[name,{kinds:[name==='frames.commands'?'command':'widget'],representations:[name==='frames.commands'?'handler':'component'],context_schema:{},ordering:'manifest'}]))
const catalog:SlotCatalogDefinitions={kinds:[{kind:'widget',schemaVersion:1,role:'widget',representations:['component'],regions:['frames.body','frames.modal'],validate:entry=>!!entry.metadata&&typeof entry.metadata==='object'&&!Array.isArray(entry.metadata)&&Object.keys(entry.metadata).every(key=>['label','manifest_order'].includes(key))&&typeof(entry.metadata as {label?:unknown}).label==='string'&&(entry.metadata as {label:string}).label.length>0&&(entry.metadata as {label:string}).label.length<=32&&Number.isSafeInteger((entry.metadata as {manifest_order?:unknown}).manifest_order),project:entry=>({label:(entry.metadata as {label:string}).label,region:entry.component!.region,manifestOrder:(entry.metadata as {manifest_order:number}).manifest_order})},{kind:'command',schemaVersion:1,role:'contribution',representations:['handler'],regions:['frames.commands'],validate:entry=>entry.handler?.id==='fixture-only',project:()=>({label:'fixture simulation',region:'frames.commands'})}],regions:[{name:'frames.body',representation:'component',kinds:['widget'],widgetKinds:['widget'],ordering:'manifest',actions:{cardinality:'optional',allowedTags:['command','navigate','modal']}},{name:'frames.modal',representation:'component',kinds:['widget'],widgetKinds:['widget'],ordering:'manifest',modal:true},{name:'frames.commands',representation:'handler',kinds:['command'],widgetKinds:[],ordering:'manifest'}],reserved:ref=>ref.owner==='host'}
export function createFrameExample(){
 const scope:HostScope={appId:'frame-demo',environmentId:'offline-fixture',clientId:'browser'}
 const isolation=store<AppIsolationSnapshot>({appId:scope.appId,effectiveMode:'sandboxed-frame',revision:'reviewed-opaque-fixture'})
 const liveScope=store<HostScope|undefined>(scope),invocation=store<Readonly<Record<string,unknown>>>({fixture:true,revision:0}),context=store<Readonly<Record<string,unknown>>>({contextLabel:'frame-context-a'})
 const navigation=store('overview'),diagnostics=store<readonly string[]>([]),status=store('loading'),allowed=store(true),hold=store(false)
 const report=(reason:string)=>diagnostics.set([...diagnostics.getSnapshot(),reason]);let admitted:PluginRegistryResponse|undefined,allowMain=false,pending:(()=>void)[]=[],disposed=false,loadEpoch=0,loadController:AbortController|undefined
 const bindings=(ref:{owner:string;kind:string;key:string})=>ref.owner==='frame-ops'&&ref.kind==='widget'&&['first','second'].includes(ref.key)?Object.entries(intents).map(([id,intent])=>({id,intent})):[]
 const actions=createFixtureActions({scope:liveScope,invocation,routes:['overview','detail'],modalRegions:['frames.modal'],commands:{'frame-tools/run':{validate:intent=>Object.keys(intent.arguments).length===0,outcome:'success'}},authorize:()=>allowed.getSnapshot(),navigate:intent=>navigation.set(intent.route),bindings:{resolve:(source,id)=>bindings(source).find(binding=>binding.id===id)?.intent},wait:()=>hold.getSnapshot()?new Promise(resolve=>pending.push(resolve)):Promise.resolve()})
 const app=createIsolatedComposition({scope,isolation,renderContext:context,actions:actions.adapter,catalog,routes:[{id:'overview',label:'Overview',path:'/',region:'frames.body'},{id:'detail',label:'Detail',path:'/detail',region:'frames.body'}],storage:memoryLayoutStorage(),registryOptions:{kinds,regions,runtimes:{react:'19.3.0'},stylesheets:false,onDiagnostic:event=>{if(event.type==='plugin-failed')report(event.error.reason);else if(event.type==='response-refused')report(event.reason)}},diagnostics:event=>report(event.reason),frame:{document,bootstrap:inventory.bootstrap,delivery:httpFrameDelivery({endpoint:'/api/frame-documents/',policyAdmitted:true,diagnostics:report}),
 review(bundle,setting){const plugin=admitted?.plugins[bundle.owner];if(!plugin||!['frame-ops','frame-tools','frame-stable'].includes(bundle.owner)||bundle.hostInstance!==admitted!.host_instance||plugin.owner_generation!==bundle.generation||plugin.bundle_version!==bundle.digest)throw new Error('unsupported-variant');return {owner:{owner:bundle.owner,generation:bundle.generation,hostInstance:bundle.hostInstance},digest:bundle.digest,mode:setting.effectiveMode,exports:bundle.owner==='frame-ops'?['FrameView','Missing']:['FrameView'],artifacts:inventory.artifacts,imports:inventory.imports}},allowMainOrigin:setting=>allowMain&&setting.revision==='explicit-reviewed-main-origin',bindings:view=>bindings(view.ref),props:(view,props)=>({label:`${view.label}: ${typeof props.contextLabel==='string'&&props.contextLabel.length<80?props.contextLabel:'unavailable'}`}),diagnostics:report}})
 actions.observe(app.runtime)
 async function load(generation='g1'){const epoch=++loadEpoch;loadController?.abort();const controller=new AbortController();loadController=controller;status.set('loading');try{const response=await fetch(`/api/frame-registry?generation=${generation}`,{signal:controller.signal});if(!response.ok)throw new Error('registry unavailable');const raw=await response.text();if(disposed||epoch!==loadEpoch||controller.signal.aborted)return;admitted=JSON.parse(raw) as PluginRegistryResponse;const result=await app.runtime.sync(raw);if(!disposed&&epoch===loadEpoch)status.set((result.registryResult as {accepted:boolean}).accepted?'ready':'frame load refused');return result}catch{if(!disposed&&epoch===loadEpoch&&!controller.signal.aborted)status.set('frame load refused')}}
 return {...app,actions,isolation,navigation,diagnostics,status,allowed,hold,load,
 complete(){for(const resolve of pending.splice(0))resolve()},changeInvocation(){invocation.set({fixture:true,revision:Number(invocation.getSnapshot().revision)+1})},changeScope(){liveScope.set({...scope,environmentId:'changed-fixture'})},changeContext(){context.set({contextLabel:'frame-context-b'})},
 async mode(authorize:boolean){allowMain=authorize;isolation.set({appId:scope.appId,effectiveMode:'main-origin',revision:authorize?'explicit-reviewed-main-origin':'main-origin-denied'});return load(authorize?'g3':'g2')},
 async dispose(){disposed=true;loadEpoch++;loadController?.abort();actions.dispose();await app.dispose()}}
}
type App=ReturnType<typeof createFrameExample>
const FrameSurfaces=memo(function FrameSurfaces({app}:{app:App}){useSyncExternalStore(app.runtime.subscribe,app.runtime.getSnapshot,app.runtime.getSnapshot);const layout=app.layouts.get('frames.body')!;useSyncExternalStore(layout.subscribe,layout.getSnapshot,layout.getSnapshot);return <section aria-label="Frame surfaces">{app.select('frames.body').map(view=><section key={view.id} aria-label={`Surface ${view.ref.key}`}><WidgetRenderer widget={view}/></section>)}</section>})
function FrameViews({app}:{app:App}){
 const layout=app.layouts.get('frames.body')!
 const status=useSyncExternalStore(app.status.subscribe,app.status.getSnapshot,app.status.getSnapshot),diagnostics=useSyncExternalStore(app.diagnostics.subscribe,app.diagnostics.getSnapshot,app.diagnostics.getSnapshot),navigation=useSyncExternalStore(app.navigation.subscribe,app.navigation.getSnapshot,app.navigation.getSnapshot),modal=useSyncExternalStore(app.actions.modal.subscribe,app.actions.modal.getSnapshot,app.actions.modal.getSnapshot),receipts=useSyncExternalStore(app.actions.receipts.subscribe,app.actions.receipts.getSnapshot,app.actions.receipts.getSnapshot)
 const target=modal&&app.select('frames.modal').find(view=>view.ref.owner===modal.target.owner&&view.ref.generation===modal.target.generation)
 const hideFirst=()=>{const first=app.runtime.getSnapshot().views.find(view=>view.ref.key==='first');if(first)layout.save({...layout.getSnapshot(),visibility:{[first.id]:false}})}
 return <main className="p-4 space-y-3 text-fg"><h1>Reviewed opaque frame consumer</h1><p>Embedded host view remains available</p><p role="status">Frame registry: {status}</p><p>Host route: {navigation}</p><FrameSurfaces app={app}/><button onClick={hideFirst}>Dispose first surface</button><button onClick={()=>{void app.registry.unload('frame-ops')}}>Unload frame owner</button><button onClick={()=>{void app.registry.unload('frame-tools')}}>Unload frame target</button><button onClick={()=>{void app.load('g2')}}>Replace generation</button><button onClick={()=>app.allowed.set(false)}>Deny fixture actions</button><button onClick={()=>app.hold.set(true)}>Hold fixture producer</button><button onClick={()=>app.complete()}>Complete frame producer</button><button onClick={()=>app.changeInvocation()}>Change frame invocation</button><button onClick={()=>app.changeScope()}>Change frame scope</button><button onClick={()=>app.changeContext()}>Change frame context</button><button onClick={()=>{void app.mode(false)}}>Request unauthorized main-origin</button><button onClick={()=>{void app.mode(true)}}>Authorize reviewed main-origin</button><section aria-label="Frame receipts">{receipts.map(receipt=><p key={receipt.id}>Fixture simulation: {receipt.status} {receipt.outcome}</p>)}</section><section aria-label="Frame diagnostics">{[...new Set(diagnostics)].map(reason=><p key={reason}>{reason}</p>)}</section><DetailDialog open={!!target} title="Frame fixture modal" onClose={()=>app.actions.closeModal()}>{target&&<WidgetRenderer widget={target}/>}</DetailDialog></main>
}
export function FrameStartup(){const[app,setApp]=useState<App>();useEffect(()=>{const next=createFrameExample();setApp(next);void next.load().catch(()=>{});return()=>{void next.dispose()}},[]);return app?<PluginHostProvider runtime={app.runtime}><FrameViews app={app}/></PluginHostProvider>:<p>Starting frame host</p>}
