import './styles.css'
import {ObservationStartup} from './observation-example.js'
import {AdminStartup} from './admin-example.js'
import {FrameStartup} from './frame-example.js'
import {DetailDialog} from '@hollis-labs/design-components'
import {createRoot} from 'react-dom/client'
import {useEffect,useState,useSyncExternalStore,useRef,lazy,Suspense} from 'react'
const AccountReviewStartup=lazy(()=>import('./account-review-example.js').then(module=>({default:module.AccountReviewStartup})));
const SettingsReviewStartup=lazy(()=>import('./settings-review-example.js').then(module=>({default:module.SettingsReviewStartup})));
const WidgetsStartup = lazy(() => import('./widgets-example.js').then(module => ({ default: module.WidgetsStartup })));
const InspectorStartup=lazy(()=>import('./inspector-example.js').then(module=>({default:module.InspectorStartup})))
const OverlayStartup=lazy(()=>import('./overlay-example.js').then(module=>({default:module.OverlayStartup})))
const DashboardStartup=lazy(()=>import('./dashboard-example.js').then(module=>({default:module.DashboardStartup})))
const PlaybackStartup=lazy(()=>import('./playback-example.js').then(module=>({default:module.PlaybackStartup})))
const ShellStartup=lazy(()=>import('./shell-example.js').then(module=>({default:module.ShellStartup})))
const VoiceStartup=lazy(()=>import('./voice-example.js').then(module=>({default:module.VoiceStartup})))
const DeveloperStartup=lazy(()=>import('./developer-example.js').then(module=>({default:module.DeveloperStartup})))
import {PluginHostProvider,WidgetRenderer,PluginPanelBody,PluginDeclarativeBody,usePluginAction,usePluginHost} from '@hollis-labs/plugin-host-ui/react'
import type {ContributionView} from '@hollis-labs/plugin-host-ui'
import {createRoutingExample} from '../src/routing-example.js'
import {createStylesheetLeases} from 'virtual:plugin-host-ui/stylesheets'
import {leasedStylesheets} from '../src/stylesheets.js'
type App=ReturnType<typeof createRoutingExample>
function Intent({view}:{view:ContributionView}){const dispatch=usePluginAction(),host=usePluginHost();const[result,setResult]=useState('');const epoch=useRef(0);useEffect(()=>{epoch.current++;setResult('');return()=>{epoch.current++}},[host,view.ref]);return <PluginDeclarativeBody view={view} render={()=> <span><button onClick={()=>{const stamp=epoch.current;void dispatch(view).then(value=>{if(stamp===epoch.current&&host.isCurrent(view))setResult(value.status)})}}>{view.label}</button><output>{result}</output></span>}/>}

function Views({app,switchContext,completePrevious}:{app:App;switchContext:()=>void;completePrevious:()=>void}){
 useSyncExternalStore(app.runtime.subscribe,app.runtime.getSnapshot,app.runtime.getSnapshot)
 const layout=app.layouts.get('operations.summary')!;useSyncExternalStore(layout.subscribe,layout.getSnapshot,layout.getSnapshot)
 const route=useSyncExternalStore(app.navigation.subscribe,app.navigation.getSnapshot,app.navigation.getSnapshot)
 const modal=useSyncExternalStore(app.actions.modal.subscribe,app.actions.modal.getSnapshot,app.actions.modal.getSnapshot)
 const receipts=useSyncExternalStore(app.actions.receipts.subscribe,app.actions.receipts.getSnapshot,app.actions.receipts.getSnapshot)
 const diagnostics=useSyncExternalStore(app.diagnostics.subscribe,app.diagnostics.getSnapshot,app.diagnostics.getSnapshot)
 const [failure,setFailure]=useState('');const widgets=app.select('operations.summary'),target=modal&&app.select('operations.modal').find(view=>view.ref.owner===modal.target.owner&&view.ref.key===modal.target.key&&view.ref.generation===modal.target.generation)
 function visibility(show:boolean){const prefs=layout.getSnapshot();const view=app.runtime.getSnapshot().views.find(view=>view.ref.key==='summary');if(view)layout.save({...prefs,visibility:{...prefs.visibility,[view.id]:show}})}
 return <main className="p-4 space-y-3 text-fg"><h1>Isolated fake control plane</h1><p>All provider observations are read-only fixtures.</p><p>Embedded application view: {app.contextKey}</p><nav aria-label="Host navigation">{app.routes.map(item=><button key={item.id} onClick={()=>app.navigation.set(item.id)}>{item.label}</button>)}</nav><nav aria-label="Plugin navigation">{app.select('operations.nav').map(view=><Intent key={view.id} view={view}/>)}</nav><section aria-label="Plugin toolbar">{app.select('operations.toolbar').map(view=><Intent key={view.id} view={view}/>)}</section><p>Current route: {route}</p>{route==='detail'&&<section aria-label="Plugin page">{app.select('operations.page').map(view=><PluginPanelBody key={view.id} panel={view}/>)}</section>}<section aria-label="Plugin widgets">{widgets.map(widget=><div key={widget.id} data-widget={widget.ref.key}><WidgetRenderer widget={widget} fallback={<p role="alert">Contribution render unavailable</p>}/></div>)}</section><section aria-label="Plugin panels">{app.select('operations.detail').map(panel=><PluginPanelBody key={panel.id} panel={panel}/>)}</section>
 <button onClick={()=>{const prefs=layout.getSnapshot();layout.save({...prefs,order:[...widgets].sort((a,b)=>Number(b.ref.owner==='stable-plugin')-Number(a.ref.owner==='stable-plugin')).map(view=>view.id)})}}>Stable first</button><button onClick={()=>visibility(false)}>Hide fixture summary</button><button onClick={()=>visibility(true)}>Show fixture summary</button>
 <button onClick={()=>{void app.registry.unload('fake-ops')}}>Unload fixture owner</button><button onClick={()=>{void app.registry.unload('fixture-tools')}}>Unload modal target</button><button onClick={switchContext}>Switch context</button><button onClick={()=>app.isolation.set({appId:'operations-demo',effectiveMode:'sandboxed-frame',revision:'require-isolated-controller'})}>Require sandbox isolation</button><button onClick={()=>app.isolation.set({appId:'operations-demo',effectiveMode:'main-origin',revision:'explicit-reviewed-offline-fixture'})}>Review fixture main-origin</button>
 <button onClick={()=>{void app.load('/api/fixture-import-registry').then(()=>setFailure(app.registry.errors().map(error=>error.reason).join(',')))}}>Try failing import</button><p role="status" aria-label="Import attempt">{failure}</p><button onClick={()=>app.completeProducer()}>Complete fixture producer</button><button onClick={completePrevious}>Complete previous fixture producer</button><section aria-label="Simulation receipts">{receipts.map(receipt=><p key={receipt.id}>Fixture simulation: {receipt.status} {receipt.outcome}</p>)}</section><section aria-label="Diagnostics">{[...new Set(diagnostics)].map(reason=><p key={reason}>{reason}</p>)}</section><DetailDialog open={!!target} onClose={()=>app.actions.closeModal()} title="Fixture presentation modal">{target&&<WidgetRenderer widget={target}/>}</DetailDialog></main>
}
function Startup(){const[app,setApp]=useState<App>(),[error,setError]=useState('');const current=useRef<App|undefined>(undefined),previous=useRef<()=>void>(()=>{}),serial=useRef(0),mounted=useRef(false),loading=useRef<AbortController|undefined>(undefined),factory=useRef<(key:string)=>App>(key=>createRoutingExample(key))
 useEffect(()=>{mounted.current=true;const controller=new AbortController();loading.current=controller;const leases=createStylesheetLeases(document);const sink=leasedStylesheets(leases,(_key,url)=>url==='/plugins/fake-ops/g1/style.css'?{owner:'fake-ops',generation:'g1'}:undefined);factory.current=key=>createRoutingExample(key,sink);const next=factory.current('context-a');current.current=next;setApp(next);void next.load('/plugins/registry',controller.signal).catch(()=>{if(mounted.current&&current.current===next&&!controller.signal.aborted)setError('Plugin registry unavailable')});return()=>{mounted.current=false;serial.current++;loading.current?.abort();const live=current.current;current.current=undefined;void (live?.dispose()??Promise.resolve()).finally(()=>{sink.dispose();leases.dispose()})}},[])
 async function switchContext(){const old=current.current;if(!old)return;current.current=undefined;previous.current=old.completeProducer;const epoch=++serial.current;loading.current?.abort();old.invalidateContext();setApp(undefined);await old.dispose();if(!mounted.current||epoch!==serial.current)return;const next=factory.current(`context-${epoch+1}`);current.current=next;const controller=new AbortController();loading.current=controller;setApp(next);try{await next.load('/plugins/registry',controller.signal)}catch{if(mounted.current&&epoch===serial.current)setError('Plugin registry unavailable')}finally{if(!mounted.current||epoch!==serial.current)await next.dispose()}}
 return error?<p role="alert">{error}</p>:app?<PluginHostProvider runtime={app.runtime}><Views key={app.contextKey} app={app} switchContext={()=>{void switchContext()}} completePrevious={()=>previous.current()}/></PluginHostProvider>:<p>Loading fixture context</p>
}
createRoot(document.getElementById('root')!).render(new URLSearchParams(location.search).has('accountReview')?<Suspense fallback={<p>Loading local account review</p>}><AccountReviewStartup/></Suspense>:new URLSearchParams(location.search).has('settingsReview')?<Suspense fallback={<p>Loading local settings review</p>}><SettingsReviewStartup/></Suspense>:new URLSearchParams(location.search).has('widgets')?<Suspense fallback={<p>Loading controlled widgets</p>}><WidgetsStartup/></Suspense>:new URLSearchParams(location.search).has('inspector')?<Suspense fallback={<p>Loading controlled inspector</p>}><InspectorStartup/></Suspense>:new URLSearchParams(location.search).has('overlays')?<Suspense fallback={<p>Loading controlled overlays</p>}><OverlayStartup/></Suspense>:new URLSearchParams(location.search).has('dashboard')?<Suspense fallback={<p>Loading controlled dashboard</p>}><DashboardStartup/></Suspense>:new URLSearchParams(location.search).has('playback')?<Suspense fallback={<p>Loading controlled playback</p>}><PlaybackStartup/></Suspense>:new URLSearchParams(location.search).has('shell')?<Suspense fallback={<p>Loading controlled shell</p>}><ShellStartup/></Suspense>:new URLSearchParams(location.search).has('voice')?<Suspense fallback={<p>Loading controlled voice</p>}><VoiceStartup/></Suspense>:new URLSearchParams(location.search).has('developer')?<Suspense fallback={<p>Loading controlled review</p>}><DeveloperStartup/></Suspense>:new URLSearchParams(location.search).has('observations')?<ObservationStartup/>:new URLSearchParams(location.search).has('admin')?<AdminStartup/>:new URLSearchParams(location.search).has('frames')?<FrameStartup/>:<Startup/> )
