import {createAdminPresentationSession} from '../src/admin-session.js';
import {store} from '../src/store.js';
import {playbackBoundaries,type createPlaybackFixture} from './playback-fixture.js';
export const authoredUsageReceipts=Object.freeze([
 {id:'zero',at:playbackBoundaries[1],inputTokens:0,outputTokens:0,totalUSD:0,inputUSD:0,outputUSD:0,note:'Authored offline zero receipt; no provider'},
 {id:'tiny',at:playbackBoundaries[2],inputTokens:1200,outputTokens:300,totalUSD:.000001,inputUSD:.0000008,outputUSD:.0000002,note:'<script>globalThis.executed = true</script>'},
 {id:'missing',at:playbackBoundaries[3],inputTokens:5,outputTokens:undefined,totalUSD:undefined,inputUSD:undefined,outputUSD:undefined,note:'Missing costs/output are absent, not free or zero'}
]);
export const capacitySpecimens=Object.freeze({receipt:{used:undefined,max:undefined},zero:{used:0,max:100},normal:{used:25,max:100},overbudget:{used:150,max:100},'zero-max':{used:0,max:0},negative:{used:-1,max:100},nan:{used:NaN,max:100},infinity:{used:Infinity,max:100}});
export type CapacitySpecimen=keyof typeof capacitySpecimens;
export type UsagePhase='ready'|'empty'|'loading'|'error'|'denied'|'unknown'|'locked'|'long';
export function createUsageEvidenceFixture(app:ReturnType<typeof createPlaybackFixture>){let disposed=false,lease=0,phase:UsagePhase='ready';let popupClose:null|{identity:string;from:number;to:number;selected:string;specimen:CapacitySpecimen}=null;const pending:(()=>void)[]=[];
 const scope=()=>{const frame=app.frame.getSnapshot(),view=app.select('operations.detail').find(v=>v.ref.owner==='fake-ops');return{identity:`${frame.contextKey}/${frame.sourceKey}/${frame.epoch}/${frame.cutoff}/${view?.ref.hostInstance}/${view?.id}/${view?.ref.generation}/${phase}`,available:!!view&&app.runtime.isCurrent(view),admitted:frame.sourceKey==='source-a'&&frame.index>=1}};
 let current=scope();const session=createAdminPresentationSession(app.frame.getSnapshot().contextKey,current.identity,['inspection']);
 const fresh=()=>({...current,phase,controlEpoch:lease,selected:'zero',specimen:'receipt' as CapacitySpecimen,popup:false,preview:false,busy:false,output:'No local usage inspection'});const state=store(fresh());
 function refresh(){if(disposed)return;const next=scope();if(next.identity===current.identity&&next.available===current.available&&next.admitted===current.admitted)return;current=next;popupClose=null;lease++;session.reset(app.frame.getSnapshot().contextKey,`${current.identity}/${current.available}/${lease}`);state.set(fresh())}
 function change(update:Partial<ReturnType<typeof fresh>>){popupClose=null;lease++;session.reset(app.frame.getSnapshot().contextKey,`${current.identity}/${lease}`);state.set({...state.getSnapshot(),...update,controlEpoch:lease,busy:false,output:'No local usage inspection'})}
 const receipts=()=>app.frame.getSnapshot().sourceKey==='source-a'?authoredUsageReceipts.filter(receipt=>receipt.at<=app.frame.getSnapshot().cutoff):[];
 function capture(){refresh();const identity=current.identity,epoch=lease,valid=()=>{refresh();return !disposed&&current.available&&current.identity===identity&&lease===epoch},editable=()=>valid()&&current.admitted&&(phase==='ready'||phase==='long');return{
  phase(value:UsagePhase){if(valid()&&['ready','empty','loading','error','denied','unknown','locked','long'].includes(value)){phase=value;refresh()}},
  select(id:string){if(editable()&&receipts().some(receipt=>receipt.id===id))change({selected:id,popup:false,preview:false})},
  specimen(value:CapacitySpecimen){if(editable()&&Object.hasOwn(capacitySpecimens,value))change({specimen:value,popup:false})},
  popup(value:boolean){if(!editable())return;if(value){change({popup:true,preview:false});return}const old=state.getSnapshot(),from=lease;if(!old.popup)return;change({popup:false});popupClose={identity:current.identity,from,to:lease,selected:old.selected,specimen:old.specimen}},preview(value:boolean){if(editable()&&(value||state.getSnapshot().preview))change(value?{preview:true,popup:false}:{preview:false})},
  hold(){if(!editable()||!state.getSnapshot().preview||state.getSnapshot().busy)return;const selected=state.getSnapshot(),target={receipt:selected.selected,specimen:selected.specimen,popup:selected.popup,preview:selected.preview},ticket=session.begin('inspection'),stamp=++lease;state.set({...selected,controlEpoch:lease,busy:true,output:'Held readonly usage candidate; no save or provider execution'});void new Promise<void>(resolve=>pending.push(resolve)).then(()=>{refresh();const live=state.getSnapshot();if(disposed||!current.available||!current.admitted||current.identity!==identity||lease!==stamp||(phase!=='ready'&&phase!=='long')||live.selected!==target.receipt||live.specimen!==target.specimen||live.popup!==target.popup||live.preview!==target.preview||!receipts().some(receipt=>receipt.id===live.selected)){ticket.cancel();return}ticket.commit(()=>state.set({...live,busy:false,output:`Inspected authored ${target.receipt} receipt locally; receipt unchanged`}))})}
 }}
 return{state,refresh,capture,receipts,current(identity:string,epoch?:number){refresh();return !disposed&&current.identity===identity&&(epoch===undefined||lease===epoch)},canRestorePopup(identity:string,epoch:number){refresh();const live=state.getSnapshot();return !disposed&&current.available&&current.identity===identity&&!!popupClose&&popupClose.identity===identity&&(epoch===popupClose.from||epoch===popupClose.to)&&lease===popupClose.to&&live.selected===popupClose.selected&&live.specimen===popupClose.specimen&&!live.popup&&!live.preview},release(){pending.splice(0).forEach(resolve=>resolve())},dispose(){if(disposed)return;disposed=true;popupClose=null;lease++;session.dispose();state.set({...fresh(),available:false,popup:false,preview:false,busy:false,output:'No local usage inspection'})}};
}
