import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {AppShell,Button} from '@hollis-labs/design-components';
import {Canvas,Node as ReviewNode,NodeHeader,NodeTitle,NodeContent,NodeDescription,NodeAction,NodeFooter,Toolbar,Panel,Connection,Edge} from '@hollis-labs/kit-workflow/canvas';
import {Position,type Node,type NodeProps,type EdgeProps,type Viewport} from '@xyflow/react';
import {PluginPanelBody,WidgetRenderer} from '@hollis-labs/plugin-host-ui/react';
import {createWorkflowReviewFixture,workflowNodes,workflowRelations,type WorkflowPhase} from './workflow-review-fixture.js';
import type {createPlaybackFixture} from './playback-fixture.js';
import {PlaybackStartup} from './playback-example.js';
import './workflow-review-style.css';
type GraphNode=Node<{title:string;description:string;select:()=>void;hold:()=>void;next:()=>void;busy:boolean},'review'>;
function FixedNode({data,selected}:NodeProps<GraphNode>){return <><ReviewNode handles={{target:true,source:true}}><NodeHeader><NodeTitle>{data.title}</NodeTitle><NodeDescription>{data.description}</NodeDescription><NodeAction><Button className="nodrag" aria-label={`Read ${data.title} metadata`} onClick={data.select}>Read</Button></NodeAction></NodeHeader><NodeContent>Fixed supplied node; no execution state</NodeContent><NodeFooter><Button className="nodrag" onClick={data.next}>Next readonly node from {data.title}</Button></NodeFooter></ReviewNode><Toolbar align="start" isVisible={selected} aria-label={`Selected ${data.title} toolbar`}><Button disabled={data.busy} onClick={data.hold}>Inspect selected {data.title}</Button></Toolbar></>}
const nodeTypes={review:FixedNode};
const graphEdges=workflowRelations.map(relation=>({...relation}));
const specimens={animated:Edge.Animated,temporary:Edge.Temporary};
function Specimens(){const props:EdgeProps={id:'authored-animation',source:'sample-a',target:'sample-b',sourceX:20,sourceY:145,targetX:250,targetY:145,sourcePosition:Position.Right,targetPosition:Position.Left,selected:false,selectable:false,deletable:false};return <section className="workflow-review-specimens kit-workflow" aria-label="Authored connection specimens"><h2>Authored visual specimens, separate from graph relationships</h2><p>Default and valid use ring color; invalid uses danger. Animated traveller is decorative only; no progress, successful connection or live processing is implied. Reduced motion hides it. Temporary line is a dashed specimen.</p><svg className="kit-workflow react-flow" viewBox="0 0 300 195" role="img" aria-label="Default valid invalid connection and decorative edge specimens"><Connection fromX={20} fromY={20} toX={250} toY={20} connectionStatus={null}/><Connection fromX={20} fromY={60} toX={250} toY={60} connectionStatus="valid"/><Connection fromX={20} fromY={100} toX={250} toY={100} connectionStatus="invalid"/><specimens.animated {...props}/><specimens.temporary {...props} id="authored-temporary" sourceY={180} targetY={180}/></svg><ul><li>Default: authored undecided geometry</li><li>Valid: authored validation appearance, not a recorded success</li><li>Invalid: authored refusal appearance</li><li>Animated: decorative traveller</li><li>Temporary: dashed proposal</li></ul></section>}
export function WorkflowReviewProof({app,retainRetired,releaseRetired,switchContext,retire}:{app:ReturnType<typeof createPlaybackFixture>;retainRetired:(release:()=>void)=>void;releaseRetired:()=>void;switchContext:()=>void;retire:()=>void}){const[fixture,setFixture]=useState<ReturnType<typeof createWorkflowReviewFixture>|null>(null);useEffect(()=>{const next=createWorkflowReviewFixture(app),releases=[app.frame.subscribe(next.refresh),app.runtime.subscribe(next.refresh)];setFixture(next);return()=>{releases.forEach(release=>release());retainRetired(next.release);next.dispose()}},[app,retainRetired]);return fixture?<WorkflowBody app={app} fixture={fixture} releaseRetired={releaseRetired} switchContext={switchContext} retire={retire}/>:<p>Loading workflow lifetime</p>}
function WorkflowBody({app,fixture,releaseRetired,switchContext,retire}:{app:ReturnType<typeof createPlaybackFixture>;fixture:ReturnType<typeof createWorkflowReviewFixture>;releaseRetired:()=>void;switchContext:()=>void;retire:()=>void}){const snapshot=useSyncExternalStore(fixture.state.subscribe,fixture.state.getSnapshot,fixture.state.getSnapshot),frame=useSyncExternalStore(app.frame.subscribe,app.frame.getSnapshot,app.frame.getSnapshot),callbacks=useMemo(()=>fixture.capture(),[fixture,snapshot.identity,snapshot.controlEpoch]),heading=useRef<HTMLHeadingElement>(null),inspector=useRef<HTMLHeadingElement>(null),previous=useRef({identity:snapshot.identity,selected:snapshot.selected});
 useEffect(()=>{const changed=snapshot.identity!==previous.current.identity,selection=snapshot.selected!==previous.current.selected;previous.current={identity:snapshot.identity,selected:snapshot.selected};if(!changed&&!selection)return;const node=changed?heading.current:inspector.current,id=requestAnimationFrame(()=>{if(fixture.current(snapshot.identity,snapshot.controlEpoch)&&node?.isConnected)node.focus()});return()=>cancelAnimationFrame(id)},[fixture,snapshot.identity,snapshot.controlEpoch,snapshot.selected]);
 const ready=snapshot.available&&snapshot.admitted&&(snapshot.phase==='ready'||snapshot.phase==='long'),view=app.select('operations.detail').find(view=>view.ref.owner==='fake-ops');
 const nodes=useMemo(()=>workflowNodes.map((node,index):GraphNode=>({id:node.id,type:'review',position:{x:index*300,y:120},selected:snapshot.selected===node.id,ariaLabel:`Readonly ${node.title} node`,data:{...node,description:snapshot.phase==='long'?`${node.description}; ${'long authored metadata '.repeat(5)}`:node.description,select:()=>callbacks.select(node.id),hold:callbacks.hold,next:()=>callbacks.select(workflowNodes[(index+1)%3].id),busy:snapshot.busy}})),[callbacks,snapshot.selected,snapshot.busy,snapshot.phase]);
 const viewport:Viewport=snapshot.viewport==='overview'?{x:25,y:25,zoom:.55}:{x:25-workflowNodes.findIndex(node=>node.id===snapshot.selected)*300,y:0,zoom:1};
 const header=<header className="workflow-review-header"><h1 ref={heading} tabIndex={-1}>Controlled workflow review</h1><p>Authored offline 3-node/2-relationship snapshot, not fake-ops business evidence. Admitted only source-a at or after boundary 2 (2026-10-05T12:00:03.100Z). Cutoff {new Date(frame.cutoff).toISOString()} is review identity, not a receipt. Read-only navigation/inspection, no editing or execution.</p><details><summary>Workflow lifecycle controls</summary><nav aria-label="Workflow lifecycle"><Button onClick={()=>app.seek(2)}>Admit authored workflow boundary</Button><Button onClick={()=>app.seek(0)}>Seek before workflow evidence</Button><Button onClick={()=>app.seek(3)}>Advance workflow cutoff</Button><Button onClick={()=>app.retireSource()}>Retire workflow source</Button><Button onClick={switchContext}>Switch workflow context</Button><Button onClick={()=>{void app.load('/api/overlay-registry')}}>Replace workflow generation</Button><Button onClick={()=>{void app.registry.unload('fake-ops')}}>Withdraw workflow owner</Button><Button onClick={retire}>Unmount workflow consumer</Button><Button onClick={fixture.release}>Release workflow producer</Button><Button onClick={releaseRetired}>Release retired workflow producer</Button></nav></details><nav aria-label="Workflow appearances">{(['ready','empty','loading','error','denied','unknown','locked','long'] as WorkflowPhase[]).map(phase=><Button key={phase} aria-pressed={snapshot.phase===phase} onClick={()=>callbacks.phase(phase)}>Workflow {phase}</Button>)}{app.select('operations.summary').filter(view=>view.ref.key==='stable').map(view=><WidgetRenderer key={`${view.id}/${frame.epoch}`} widget={view}/>)}</nav></header>;
 return <AppShell header={header}><div className="workflow-review-scroll" role="region" aria-label="Workflow readonly review">{!ready?<section role={snapshot.phase==='error'?'alert':'status'}><h2>Workflow {snapshot.available?(snapshot.admitted?snapshot.phase:'not yet admitted'):'withdrawn'}</h2><p>{snapshot.phase==='empty'&&snapshot.admitted?'Successful empty authored snapshot: 0 nodes / 0 relationships.':'Current supported graph unavailable; no successful zero counts or future metadata exposed.'}</p></section>:<><div className="workflow-review-columns"><section aria-label="Fixed workflow graph"><p>3 authored nodes / 2 declared relationships. Graph positions and relationships remain fixed. Native alternatives below do not require dragging or graph keyboard gestures.</p><div className="workflow-review-canvas"><Canvas key={snapshot.identity} nodes={nodes} edges={graphEdges} nodeTypes={nodeTypes} viewport={viewport} nodesDraggable={false} nodesConnectable={false} edgesReconnectable={false} deleteKeyCode={null} panOnDrag={false} zoomOnScroll={false} zoomOnPinch={false} zoomOnDoubleClick={false} onNodeClick={(_event,node)=>callbacks.select(node.id)} onNodesChange={changes=>{const selected=changes.find(change=>change.type==='select'&&change.selected);if(selected?.type==='select')callbacks.select(selected.id)}} ariaLabelConfig={{'node.a11yDescription.default':'Readonly authored nodes. Use native node controls below.'}}><Panel position="top-left" aria-label="Readonly graph panel"><Button aria-pressed={snapshot.viewport==='overview'} onClick={()=>callbacks.viewport('overview')}>Overview viewport</Button><Button aria-pressed={snapshot.viewport==='detail'} onClick={()=>callbacks.viewport('detail')}>Selected node viewport</Button></Panel></Canvas></div><nav aria-label="Native workflow nodes">{workflowNodes.map(node=><Button key={node.id} aria-pressed={snapshot.selected===node.id} onClick={()=>callbacks.select(node.id)}>Select {node.title} node</Button>)}</nav><nav aria-label="Declared workflow relationships">{workflowRelations.map(relation=><Button key={relation.id} onClick={()=>callbacks.relationship(relation.id)}>Read {relation.source} to {relation.target}</Button>)}</nav></section><section aria-label="Workflow readonly inspector"><h2 ref={inspector} tabIndex={-1}>Readonly {snapshot.selected} metadata</h2><pre>{JSON.stringify(workflowNodes.find(node=>node.id===snapshot.selected),null,2)}</pre><p>Viewport {snapshot.viewport}; fixed authored metadata unchanged.</p><Button disabled={snapshot.busy} onClick={callbacks.hold}>Hold readonly workflow inspection</Button><Button onClick={fixture.release}>Release held workflow inspection</Button><p role="status" aria-label="Workflow inspection outcome">{snapshot.output}</p>{view&&app.runtime.isCurrent(view)&&<PluginPanelBody panel={view}/>}</section></div><Specimens/></>}</div></AppShell>;
}
export function WorkflowReviewStartup(){const retired=useRef<()=>void>(()=>{}),retain=useRef((release:()=>void)=>{retired.current=release}),release=useRef(()=>retired.current());return <PlaybackStartup workflowReview retainWorkflowProducer={retain.current} releaseWorkflowProducer={release.current}/>}
